import { lazy, Suspense, useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { Activity, ArrowDownLeft, ArrowUpRight, Bell, Bookmark, Check, ChevronDown, ChevronRight, CircleHelp, Compass, Disc3, Download, Ellipsis, Film, Fingerprint, Gamepad2, Globe2, Heart, Home, ImagePlus, Layers3, Leaf, MessageCircle, MessageSquare, MoreHorizontal, Plus, Search, Send, ShoppingBag, Sparkles, Store, Sun, TrendingUp, Users, Wallet, Wrench, X, Zap } from 'lucide-react';
import { fmt, initialPosts, opportunities, products, type FeedPost } from '../data/seed';
import { loadState, saveState, type SavedState } from '../lib/storage';
import { apiUrl } from '../lib/api';
import Sidekick from './assistant/Sidekick';
import QuickHandi from './quickhandi/QuickHandi';
import MarketplaceHub, { type CommerceProduct } from './MarketplaceHub';
import { PeopleToFollow, ReelsPage, StoriesStrip } from './SocialHub';
import { BaobabDawn, ConnectionField, GlowGrid, PatternBackdrop } from './africa-art';
const Communications = lazy(() => import('./Communications'));
const HomeDepth = lazy(() => import('./HomeDepth'));
const BackendWorkspace = lazy(() => import('./backend/BackendWorkspace'));

type Page = 'Home'|'Explore'|'Create'|'Messages'|'Calls & Live'|'Reels'|'Profile'|'Marketplace'|'Opportunities'|'Gaming'|'Communities'|'Quick&Handi'|'EcoVibes ID'|'Rewards'|'Wallet'|'Settings';
const navItems: {page:Page; icon:typeof Home; label:string}[] = [{page:'Home',icon:Home,label:'Home'},{page:'Explore',icon:Compass,label:'Explore'},{page:'Create',icon:Plus,label:'Create'},{page:'Messages',icon:MessageCircle,label:'Messages'},{page:'Calls & Live',icon:Activity,label:'Calls & Live'},{page:'Profile',icon:Users,label:'Profile'},{page:'EcoVibes ID',icon:Fingerprint,label:'EcoVibes ID'}];
const initials=(s:string)=>s.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
function Avatar({label,size='md',className=''}:{label:string;size?:'sm'|'md'|'lg';className?:string}){return <span className={`avatar avatar-${size} ${className}`}>{label}</span>}
function Button({children,onClick,kind='secondary',className='',disabled=false}:{children:ReactNode;onClick?:()=>void;kind?:'primary'|'secondary'|'quiet';className?:string;disabled?:boolean}){return <button disabled={disabled} onClick={onClick} className={`button button-${kind} ${className}`}>{children}</button>}
function App(){
 const [page,setPage]=useState<Page>('Home');
 const [state,setState]=useState<SavedState>(()=>loadState());
 const [displayName,setDisplayName]=useState<string|null>(null);
 const [online,setOnline]=useState(navigator.onLine);
 const [query,setQuery]=useState('');
 const [toast,setToast]=useState('');
 const [cartOpen,setCartOpen]=useState(false);
 const [showComposer,setShowComposer]=useState(false);
 const [message,setMessage]=useState('');
 const [searchOpen,setSearchOpen]=useState(false);
 const [feedTab,setFeedTab]=useState('For you');
 const [category,setCategory]=useState('All');
 const [activeChat,setActiveChat]=useState('Esi Owusu');
 const [sellerProducts,setSellerProducts]=useState<CommerceProduct[]>(()=>{try{return JSON.parse(localStorage.getItem('ecovibes:marketplace-products:v1')||'[]')}catch{return []}});
 const dateLabel=new Intl.DateTimeFormat('en-GH',{weekday:'long',day:'numeric',month:'long',timeZone:'Africa/Accra'}).format(new Date()).toUpperCase();
 const greetingHour=Number(new Intl.DateTimeFormat('en-GH',{hour:'numeric',hourCycle:'h23',timeZone:'Africa/Accra'}).format(new Date()));
 const greeting=greetingHour<12?'morning':greetingHour<17?'afternoon':'evening';
 useEffect(()=>saveState(state),[state]);
 useEffect(()=>{try{localStorage.setItem('ecovibes:marketplace-products:v1',JSON.stringify(sellerProducts))}catch{/* Keep marketplace preview usable when storage is unavailable. */}},[sellerProducts]);
 useEffect(()=>{const up=()=>setOnline(true),down=()=>setOnline(false);window.addEventListener('online',up);window.addEventListener('offline',down);return()=>{window.removeEventListener('online',up);window.removeEventListener('offline',down)}},[]);
 useEffect(()=>{if(page!=='Home'||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const region=document.querySelector('.home-layout');if(!region)return;const selector='.quick-card,.quickhandi-home-card';const reset=(card:Element)=>{const el=card as HTMLElement;el.style.setProperty('--card-tilt-x','0deg');el.style.setProperty('--card-tilt-y','0deg');el.style.setProperty('--shine-x','50%');el.style.setProperty('--shine-y','0%');};const move=(event:Event)=>{const pointer=event as PointerEvent;const card=(pointer.target as Element|null)?.closest(selector) as HTMLElement|null;if(!card||!region.contains(card))return;const rect=card.getBoundingClientRect();const x=(pointer.clientX-rect.left)/rect.width;const y=(pointer.clientY-rect.top)/rect.height;card.style.setProperty('--card-tilt-x',`${((.5-y)*12).toFixed(2)}deg`);card.style.setProperty('--card-tilt-y',`${((x-.5)*12).toFixed(2)}deg`);card.style.setProperty('--shine-x',`${(x*100).toFixed(1)}%`);card.style.setProperty('--shine-y',`${(y*100).toFixed(1)}%`);};const leave=(event:Event)=>{const pointer=event as PointerEvent;const card=(pointer.target as Element|null)?.closest(selector);const next=pointer.relatedTarget instanceof Element?pointer.relatedTarget.closest(selector):null;if(card&&card!==next)reset(card);};region.addEventListener('pointermove',move,{passive:true});region.addEventListener('pointerout',leave,{passive:true});return()=>{region.removeEventListener('pointermove',move);region.removeEventListener('pointerout',leave);};},[page]);
 useEffect(()=>{const sendPresence=async()=>{if(document.visibilityState!=='visible')return;try{const me=await fetch(apiUrl('/auth/me'),{credentials:'include'}).then(r=>r.json());setDisplayName(me.user?.display_name||null);if(me.user&&me.csrfToken)await fetch(apiUrl('/people/presence'),{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','X-CSRF-Token':me.csrfToken},body:'{}'});}catch{/* Presence stays optional if the API is offline. */}};void sendPresence();const timer=window.setInterval(sendPresence,60_000);const visible=()=>void sendPresence();document.addEventListener('visibilitychange',visible);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',visible);};},[page]);
 useEffect(()=>{const navigate=(event:Event)=>go((event as CustomEvent<Page>).detail);window.addEventListener('ecovibes:navigate',navigate);return()=>window.removeEventListener('ecovibes:navigate',navigate);},[]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(id)},[toast]);
 const posts=useMemo(()=>[...state.posts,...initialPosts].filter(p=>`${p.name} ${p.text} ${p.tag}`.toLowerCase().includes(query.toLowerCase())),[state.posts,query]);
 const catalogProducts:CommerceProduct[]=[...sellerProducts,...products];
 const cartCount=Object.values(state.cart).reduce((a,b)=>a+b,0);
 const total=catalogProducts.reduce((sum,p)=>sum+p.price*(state.cart[p.id]||0),0);
 const go=(p:Page)=>{setPage(p);setSearchOpen(false);window.scrollTo({top:0,behavior:'smooth'});};
 const patch=(data:Partial<SavedState>)=>setState(s=>({...s,...data}));
 const notify=(s:string)=>setToast(s);
 const addCart=(id:string)=>{patch({cart:{...state.cart,[id]:(state.cart[id]||0)+1}});notify('Added to your bag');};
 const toggle=(key:'liked'|'saved'|'followed'|'savedOpps',id:string)=>{const list=state[key];patch({[key]:list.includes(id)?list.filter(x=>x!==id):[...list,id]});};
 const submitPost=(e:FormEvent)=>{e.preventDefault();if(!state.draft.trim())return;const post:FeedPost={id:`draft-${Date.now()}`,name:'You',handle:'you',time:'Just now',text:state.draft.trim(),tag:'COMMUNITY',likes:0,comments:0,avatar:'YO'};patch({posts:[post,...state.posts],draft:''});setShowComposer(false);notify('Your post is on EcoVibes');};
 const sendMessage=(e:FormEvent)=>{e.preventDefault();if(!message.trim())return;notify('Message sent');setMessage('');};
 const checkout=()=>{if(!cartCount)return;notify('Sandbox order created · no payment was taken');patch({cart:{}});setCartOpen(false);};
 return <div className={`app theme-${state.theme} mode-${state.saver}`}>
  {!online&&<div className="offline-bar"><Globe2 size={14}/> You’re offline. Saved content is still available.</div>}
  <aside className="sidebar">
   <div className="brand" onClick={()=>go('Home')} role="button" tabIndex={0}><span className="brand-mark"><Leaf size={21}/></span><span>eco<span className="brand-v">vibes</span></span></div>
   <button className="workspace-pill"><span className="workspace-dot"/> Your space <ChevronDown size={15}/></button>
   <p className="side-label">YOUR SPACE</p>
   <nav className="side-nav">{navItems.filter(n=>n.page!=='Create').map(({page:p,icon:Icon,label})=><button key={p} onClick={()=>go(p)} className={page===p?'active':''}><Icon size={18}/><span>{label}</span>{p==='Messages'&&<b className="nav-count">2</b>}</button>)}</nav>
   <p className="side-label explore-label">YOUR ECOSYSTEM</p>
   <nav className="side-nav">{([{p:'Quick&Handi',i:Wrench},{p:'Marketplace',i:Store},{p:'Gaming',i:Gamepad2},{p:'Reels',i:Film},{p:'Opportunities',i:Sparkles},{p:'Rewards',i:Zap},{p:'Wallet',i:Wallet}] as const).map(({p,i:Icon})=><button key={p} onClick={()=>go(p)} className={page===p?'active':''}><Icon size={18}/><span>{p}</span></button>)}</nav>
   <div className="side-bottom"><div className="saver-note"><div className="saver-icon"><Zap size={16}/></div><div><b>Data saver is on</b><span>Less data, more doing.</span></div><button aria-label="Open data settings" onClick={()=>go('Settings')}><ChevronRight size={16}/></button></div><button className="side-profile" onClick={()=>go('Profile')}><Avatar label="PK"/><span><b>Philip K.</b><small>View profile</small></span><MoreHorizontal size={18}/></button></div>
  </aside>
  <div className="main-column">
   <header className="topbar"><div className="mobile-brand" onClick={()=>go('Home')}><span className="brand-mark"><Leaf size={19}/></span>ecovibes</div><div className="crumb"><span>EcoVibes</span><ChevronRight size={14}/><b>{page}</b></div><div className="top-actions"><button className="icon-button search-trigger" aria-label="Search" onClick={()=>setSearchOpen(v=>!v)}><Search size={18}/></button><button className="icon-button" aria-label="Notifications" onClick={()=>notify('You’re all caught up')}><Bell size={18}/><i/></button><button className="bag-button" onClick={()=>setCartOpen(true)}><ShoppingBag size={17}/><span>Bag</span>{cartCount>0&&<b>{cartCount}</b>}</button></div></header>
   {searchOpen&&<div className="search-panel"><Search size={18}/><input autoFocus placeholder="Search people, products, games…" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>setSearchOpen(false)} aria-label="Close search"><X size={17}/></button><Button kind="primary" onClick={()=>go('Explore')}>Search</Button></div>}
   <main className="page-content">
    {page==='Home'&&<><div className="home-layout"><section className="feed-column"><div className="welcome-row"><div><p className="eyebrow">{dateLabel}</p><h1>{displayName ? 'Good '+greeting+', '+displayName.split(' ')[0] : 'Welcome to EcoVibes'} <span>✳</span></h1><p className="subhead">A little bit of everything, all in one place.</p></div><button className="round-action" aria-label="Create a post" onClick={()=>setShowComposer(true)}><Plus size={21}/></button></div>
      <StoriesStrip onSignIn={()=>go('EcoVibes ID')}/><section className="ecosystem-hero" data-image-slot="Hero banner"><PatternBackdrop motif="weave" color="#b28c4c" intensity={.11}/><GlowGrid color="#7eaa6d" intensity={.16}/><BaobabDawn/><ConnectionField/><div className="ecosystem-copy"><span className="eyebrow">YOUR WORLD, CONNECTED</span><h2>One EcoVibes ID.<br/><em>Room for your whole world.</em></h2><p>Connect, create, play, trade and grow from one place.</p><button onClick={()=>go('EcoVibes ID')}>Explore your EcoVibes ID <ChevronRight size={15}/></button></div><div className="ecosystem-art"><Suspense fallback={<div className="home-depth-fallback" aria-hidden="true"><Leaf size={56}/></div>}><HomeDepth/></Suspense><div className="depth-label">YOUR WORLD<br/><b>IN MOTION</b></div><span className="image-slot-label">HERO · IMAGE SLOT</span></div></section>
      <section className="quickhandi-home-card" data-image-slot="Quick&Handi"><PatternBackdrop motif="mudcloth" color="#a56a4e" intensity={.08}/><GlowGrid color="#79a66c" intensity={.14}/><div className="quickhandi-home-copy"><span className="qh-home-label"><Wrench size={15}/> ECOVIBES · QUICK&HANDI</span><h2>Need something done?</h2><p>Find local professionals for everyday jobs, creative work and more.</p><div><button onClick={()=>go('Quick&Handi')}>Find a Service <ArrowHomeIcon/></button><button onClick={()=>go('Quick&Handi')}>Become a Handi <Plus size={15}/></button></div></div><div className="qh-home-art" aria-hidden="true"><span className="qh-home-orbit qh-home-orbit-a"/><span className="qh-home-orbit qh-home-orbit-b"/><span className="qh-home-core"><Wrench size={25}/></span><span className="qh-home-tag qh-tag-one">LOCAL</span><span className="qh-home-tag qh-tag-two">ON YOUR TERMS</span><span className="image-slot-label">QUICK&HANDI · IMAGE SLOT</span></div></section>
      <div className="quick-grid">{[{name:'Marketplace',icon:ShoppingBag,tint:'quick-peach',meta:'Discover local finds',pg:'Marketplace' as Page,motif:'mudcloth' as const,color:'#ac7457'},{name:'Gaming',icon:Gamepad2,tint:'quick-lilac',meta:'Play with your people',pg:'Gaming' as Page,motif:'nde' as const,color:'#7f78b0'},{name:'Opportunities',icon:Sparkles,tint:'quick-blue',meta:'Find what’s next',pg:'Opportunities' as Page,motif:'adinkra' as const,color:'#718b70'}].map(({name,icon:Icon,tint,meta,pg,motif,color})=><button key={name} className="quick-card" data-image-slot={name} onClick={()=>go(pg)}><PatternBackdrop motif={motif} color={color} intensity={.1}/><span className={`quick-icon ${tint}`}><Icon size={19}/></span><span className="quick-name">{name}</span><small>{meta}</small><ChevronRight className="quick-arrow" size={16}/><span className="image-slot-label">{name.toUpperCase()} · IMAGE SLOT</span></button>)}</div>
      <div className="section-title feed-heading"><div><h2>Your community</h2><p>Good things are happening around you.</p></div><div className="social-home-actions"><button className="text-link" onClick={()=>go('Reels')}><Film size={14}/> Watch Reels</button><button className="text-link" onClick={()=>go('Explore')}>Explore all <ChevronRight size={15}/></button></div></div>
      <div className="feed-tabs">{['For you','Following','Nearby'].map(t=><button onClick={()=>setFeedTab(t)} className={feedTab===t?'selected':''} key={t}>{t}</button>)}</div>
      <button className="compose-prompt" onClick={()=>setShowComposer(true)}><Avatar label="PK"/><span>Share something with your community…</span><span className="compose-plus"><Plus size={18}/></span></button>
      <div className="feed-list">{posts.map(post=><PostCard key={post.id} post={post} liked={state.liked.includes(post.id)} saved={state.saved.includes(post.id)} onLike={()=>toggle('liked',post.id)} onSave={()=>toggle('saved',post.id)} onComment={()=>go('Messages')}/>)}{posts.length===0&&<Empty title="No posts found" detail="Try another search or share something new."/>}</div>
     </section><aside className="home-rail"><div className="rail-card trend-card"><div className="rail-heading"><h3><TrendingUp size={16}/> Happening now</h3><button aria-label="More trends"><Ellipsis size={18}/></button></div><button className="trend-item" onClick={()=>go('Explore')}><span className="trend-rank">01</span><span><b>#MadeInGhana</b><small>2.4k conversations</small></span><ChevronRight size={15}/></button><button className="trend-item" onClick={()=>go('Gaming')}><span className="trend-rank">02</span><span><b>Weekend Arena</b><small>Gaming · 840 playing</small></span><ChevronRight size={15}/></button><button className="trend-item" onClick={()=>go('Opportunities')}><span className="trend-rank">03</span><span><b>Open Call: Creators</b><small>Opportunity · 3 days left</small></span><ChevronRight size={15}/></button></div>
       <PeopleToFollow onSignIn={()=>go('EcoVibes ID')}/>
       <div className="mini-promo"><span className="promo-spark">✳</span><p className="eyebrow">MADE FOR YOUR DATA</p><h3>More of what matters.<br/>Less of what doesn’t.</h3><p>EcoVibes works with your connection, not against it.</p><button onClick={()=>go('Settings')}>Your data settings <ChevronRight size={14}/></button></div>
       <footer className="rail-footer">About · Community guidelines · Privacy<br/>© 2026 EcoVibes <span>Built for more.</span></footer>
      </aside></div></>}
    {page==='Explore'&&<><PageTitle eyebrow="FIND YOUR NEXT THING" title="Explore" desc="People, ideas and opportunities worth your time."/><div className="explore-search"><Search size={18}/><input placeholder="Search EcoVibes" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><div className="category-pills">{['All','Creators','Community','Games','Marketplace','Opportunities'].map(c=><button className={category===c?'chosen':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="explore-feature"><div><span className="eyebrow">THE ECOVIBES EDIT</span><h2>Fresh perspectives,<br/>close to home.</h2><p>Discover makers, players and people building something good.</p><Button kind="primary" onClick={()=>setCategory('Creators')}>Meet the community <ChevronRight size={16}/></Button></div><div className="feature-art"><span className="art-sun"/><span className="art-arch"/><span className="art-leaf">✳</span><span className="art-label">FIND<br/>YOUR<br/>PEOPLE</span></div></div><div className="section-title explore-section-title"><div><h2>{category==='All'?'Picked for you':category}</h2><p>Small discoveries can lead somewhere.</p></div></div><div className="discover-grid">{category!=='Marketplace'&&<DiscoverCard icon={<Users/>} label="COMMUNITY" title="People making things happen" detail="Meet your next collaborator." onClick={()=>go('Communities')}/ >}{category!=='Opportunities'&&<DiscoverCard icon={<Gamepad2/>} label="GAMING" title="One more round?" detail="Find a game and join in." onClick={()=>go('Gaming')}/ >}{category!=='Games'&&<DiscoverCard icon={<Store/>} label="MARKETPLACE" title="Thoughtful things, made here" detail="Independent sellers. Real stories." onClick={()=>go('Marketplace')}/ >}{category!=='Creators'&&<DiscoverCard icon={<Sparkles/>} label="OPPORTUNITIES" title="Your next open door" detail="Grants, work and events." onClick={()=>go('Opportunities')}/ >}</div></>}
    {page==='EcoVibes ID'&&<Suspense fallback={<div className="media-loading">Opening EcoVibes ID…</div>}><BackendWorkspace/></Suspense>}
    {page==='Calls & Live'&&<Suspense fallback={<div className="media-loading">Opening Calls & Live…</div>}><Communications/></Suspense>}
    {page==='Reels'&&<ReelsPage onSignIn={()=>go('EcoVibes ID')}/>}
    {page==='Marketplace'&&<><PageTitle eyebrow="THE ECOVIBES MARKETPLACE" title="Good things, made by good people." desc="Discover products from local sellers, connected stores and authorized suppliers." action={<Button onClick={()=>setCartOpen(true)}><ShoppingBag size={16}/> Your bag {cartCount>0&&`(${cartCount})`}</Button>}/><MarketplaceHub products={catalogProducts} onProductsChange={setSellerProducts} onAddCart={addCart} onToggleSaved={id=>toggle('saved',id)} saved={state.saved} onOpenWorkspace={()=>go('EcoVibes ID')}/><div className="qh-delivery-callout"><span><Wrench size={17}/></span><div><b>Need help getting it there?</b><small>Explore local delivery and errands in Quick&Handi.</small></div><button onClick={()=>go('Quick&Handi')}>Find a courier <ChevronRight size={14}/></button></div></>}
    {page==='Opportunities'&&<><PageTitle eyebrow="ROOM TO GROW" title="Opportunities" desc="A new project, a fresh start, a way forward." action={<Button kind="primary" onClick={()=>notify('Opportunity alerts enabled')}>Get alerts <Bell size={15}/></Button>}/><div className="opportunity-intro"><div><span className="eyebrow">GOOD THINGS ARE OUT THERE</span><h2>Make your next move.</h2><p>Thoughtful opportunities for people building what’s next.</p></div><div className="opportunity-stats"><span><b>Open now</b><small>Curated weekly</small></span><Sparkles size={23}/></div></div><div className="category-pills">{['All','Creator grants','Freelance','Community','Events'].map(c=><button key={c} className={category===c?'chosen':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="opportunity-list">{opportunities.map((o,i)=><article className="opportunity-card" key={o.id}><div className={`opp-number ${o.tone}`}>0{i+1}</div><div className="opp-main"><span className="eyebrow">{o.type}</span><h3>{o.title}</h3><p>{o.org}</p><div className="opp-meta"><span><Globe2 size={14}/>{o.place}</span><span><Activity size={14}/>{o.due}</span></div></div><button className={`save-opportunity ${state.savedOpps.includes(o.id)?'saved':''}`} onClick={()=>toggle('savedOpps',o.id)}>{state.savedOpps.includes(o.id)?<Check size={16}/>:<Bookmark size={16}/>}<span>{state.savedOpps.includes(o.id)?'Saved':'Save'}</span></button></article>)}</div><div className="trust-note"><CircleHelp size={17}/><span>Each listing is reviewed before it appears. Always check the organizer’s details before sharing personal information.</span></div></>}
    {page==='Gaming'&&<><PageTitle eyebrow="PLAY TOGETHER" title="Gaming" desc="Good games are better with good company." action={<Button kind="primary" onClick={()=>notify('Game profiles are coming soon')}>Your game profile <ChevronRight size={15}/></Button>}/><div className="game-hero"><div><span className="eyebrow">THIS WEEK’S COMMUNITY CHALLENGE</span><h2>Weekend<br/>Arena</h2><p>Quick rounds. Friendly rivals.<br/>Your leaderboard starts here.</p><Button kind="primary" onClick={()=>notify('Challenge lobby · coming soon')}>View challenge <ChevronRight size={16}/></Button></div><div className="game-orbit"><span className="orbit-ring ring-one"/><span className="orbit-ring ring-two"/><Gamepad2 size={54}/><b>PLAY<br/>TOGETHER</b></div></div><div className="section-title"><div><h2>Find your next game</h2><p>Lightweight ways to play, at your pace.</p></div><span className="coming-label">COMMUNITY PICKS</span></div><div className="game-grid"><GameTile title="Word Sprint" type="PUZZLE · 2–8 PLAYERS" colors="game-mint" icon="Aa" onClick={()=>notify('Word Sprint · game integration coming soon')}/><GameTile title="Goal Line" type="ARCADE · QUICK PLAY" colors="game-coral" icon="↗" onClick={()=>notify('Goal Line · game integration coming soon')}/><GameTile title="Mancala Circle" type="STRATEGY · 2 PLAYERS" colors="game-sand" icon="◉" onClick={()=>notify('Mancala Circle · game integration coming soon')}/></div><div className="info-strip"><Gamepad2 size={18}/><span>Games are designed to use little data. Playable game integrations are being built.</span><button onClick={()=>notify('You’ll hear when games launch')}>Notify me</button></div></>}
    {page==='Create'&&<><PageTitle eyebrow="MAKE SOMETHING" title="Create" desc="Put an idea into the world. The right people will find it."/><div className="create-options">{[{icon:MessageSquare,title:'Write a post',detail:'Share a thought, a moment or a question.',color:'create-sage',action:()=>setShowComposer(true)},{icon:ImagePlus,title:'Share a photo',detail:'Add an image to your community feed.',color:'create-peach',action:()=>notify('Photo uploads will be available when media storage is connected.')},{icon:Store,title:'List a product',detail:'Bring your work to the marketplace.',color:'create-lilac',action:()=>go('EcoVibes ID')},{icon:Sparkles,title:'Share an opportunity',detail:'Help someone find their next step.',color:'create-blue',action:()=>notify('Opportunity submissions are being prepared.')}].map(({icon:Icon,title,detail,color,action})=><button className="create-option" onClick={action} key={title}><span className={`create-icon ${color}`}><Icon size={21}/></span><span><b>{title}</b><small>{detail}</small></span><ChevronRight size={17}/></button>)}</div><div className="draft-card"><div><span className="eyebrow">SAVED ON THIS DEVICE</span><h3>Your drafts are here when you need them.</h3><p>Drafts stay on this device and can be edited offline.</p></div><span className="draft-icon"><Bookmark size={19}/></span><button className="draft-edit" onClick={()=>setShowComposer(true)}>Write a draft <ChevronRight size={15}/></button></div></>}
    {page==='Quick&Handi'&&<QuickHandi/>}
    {page==='Communities'&&<><PageTitle eyebrow="FIND YOUR PEOPLE" title="Communities" desc="Interest groups and local circles, connected to everything else." action={<Button kind="primary" onClick={()=>notify('Community creation will be available when accounts are connected.')}>Start a community <Plus size={15}/></Button>}/><div className="community-hero"><div><span className="eyebrow">SHARED INTERESTS · REAL CONNECTIONS</span><h2>Better together.<br/>Built around what you love.</h2><p>Meet people, find events and discover opportunities from the same place.</p></div><div className="community-orb" aria-hidden="true"><span/><i/><b><Users size={30}/></b></div></div><div className="section-title"><div><h2>Communities to explore</h2><p>Find your people across EcoVibes.</p></div></div><div className="community-grid">{[{icon:'✳',name:'Ghana game makers',desc:'Players, indie developers and tournament hosts.',members:'1.2k members',tone:'community-green'},{icon:'◒',name:'Made in Ghana',desc:'Independent makers and thoughtful local finds.',members:'840 members',tone:'community-peach'},{icon:'Aa',name:'Creators’ corner',desc:'Share work, find collaborators and grow together.',members:'2.1k members',tone:'community-lilac'},{icon:'↗',name:'Next step network',desc:'Grants, freelance work and opportunities.',members:'690 members',tone:'community-blue'}].map(group=><article className="community-card" key={group.name}><div className={`community-art ${group.tone}`}><span>{group.icon}</span><i/><b>{group.members}</b></div><div className="community-card-copy"><span className="eyebrow">COMMUNITY</span><h3>{group.name}</h3><p>{group.desc}</p><Button onClick={()=>notify('Community previews are available. Membership sync is not connected.')}>View community <ChevronRight size={14}/></Button></div></article>)}</div></>}
    {page==='Messages'&&<><PageTitle eyebrow="YOUR CONVERSATIONS" title="Messages" desc="Good conversations, without the extra noise."/><div className="messages-layout"><aside className="conversation-list"><div className="conversation-tools"><b>Inbox <span>3</span></b><button aria-label="New message" onClick={()=>notify('Choose someone from Explore to start a chat.')}><Plus size={17}/></button></div>{[{name:'Esi Owusu',msg:'That sounds perfect, see you then!',time:'2m',avatar:'EO',active:true},{name:'Ama Serwaa',msg:'Sent you the new collection ✨',time:'1h',avatar:'AS'},{name:'Weekend Arena',msg:'Nana: anyone on for a round?',time:'3h',avatar:'WA',group:true}].map(c=><button key={c.name} onClick={()=>setActiveChat(c.name)} className={`conversation ${activeChat===c.name?'selected':''}`}><Avatar label={c.avatar} className={c.group?'avatar-group':''}/><span><b>{c.name}</b><small>{c.msg}</small></span><time>{c.time}</time></button>)}</aside><section className="chat-panel"><div className="chat-head"><Avatar label={initials(activeChat)}/><span><b>{activeChat}</b><small><i/> Active recently</small></span><button aria-label="Conversation settings" onClick={()=>notify('Conversation settings')}><MoreHorizontal size={19}/></button></div><div className="chat-body"><div className="chat-date">TODAY · 6:42 PM</div><div className="chat-message theirs">Hey! Are you free to check out the new makers market this weekend?<small>6:42 PM</small></div><div className="chat-message mine">I’d love to. Saturday afternoon works for me!<small>6:45 PM <Check size={12}/></small></div><div className="chat-message theirs">That sounds perfect, see you then!<small>6:47 PM</small></div><div className="chat-offline-note"><Zap size={13}/> Messages use very little data</div></div><form className="chat-compose" onSubmit={sendMessage}><button type="button" aria-label="Attach file" onClick={()=>notify('Attachments are coming soon')}><Plus size={19}/></button><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a message…" aria-label="Write a message"/><button type="submit" className="send-button" aria-label="Send message"><Send size={17}/></button></form></section></div></>}
    {page==='Profile'&&<><div className="profile-cover"><span className="cover-shape cover-shape-one"/><span className="cover-shape cover-shape-two"/><Button className="edit-profile" onClick={()=>notify('Profile editor opened')}>Edit profile</Button></div><div className="profile-head"><Avatar label="PK" size="lg" className="profile-avatar"/><div className="profile-identity"><h1>Philip Konyah <span className="verified"><Check size={13}/></span></h1><p>@philipk · Accra, Ghana</p><p className="profile-bio">Curious about the people and ideas making everyday life a little better.</p><div className="profile-stats"><span><b>12</b> posts</span><span><b>248</b> followers</span><span><b>186</b> following</span></div></div></div><div className="profile-tabs"><button className="selected">Activity</button><button onClick={()=>notify('Your saved items are on this device')}>Saved <span>{state.saved.length}</span></button><button onClick={()=>go('Rewards')}>Rewards</button><button onClick={()=>go('Settings')}>Settings</button></div><div className="profile-activity"><div className="section-title"><div><h2>Your activity</h2><p>Things you’ve shared with the community.</p></div></div>{state.posts.length?state.posts.map(p=><PostCard key={p.id} post={p} liked={state.liked.includes(p.id)} saved={state.saved.includes(p.id)} onLike={()=>toggle('liked',p.id)} onSave={()=>toggle('saved',p.id)} onComment={()=>go('Messages')}/>):<Empty title="Your story starts here" detail="Share a thought, meet your community and make this space yours."><Button kind="primary" onClick={()=>setShowComposer(true)}>Write your first post <Plus size={16}/></Button></Empty>}</div></>}
    {page==='Rewards'&&<><PageTitle eyebrow="A LITTLE RECOGNITION" title="Rewards" desc="Good things grow when we show up for each other."/><div className="reward-card"><div className="reward-top"><span className="eyebrow">YOUR ECOVIBES POINTS</span><span className="reward-stamp"><Zap size={15}/></span></div><div className="reward-number">240<span> pts</span></div><p>Keep contributing to your community. Points are for recognition and have no cash value.</p><div className="reward-progress"><span/><i/></div><div className="reward-next"><span>Community regular</span><b>60 pts to your next badge</b></div></div><div className="section-title reward-title"><div><h2>Your badges</h2><p>Milestones you’ve earned by being here.</p></div></div><div className="badges-grid"><Badge icon="✳" title="First hello" detail="Joined the community" earned/><Badge icon="♡" title="Good neighbour" detail="Helped someone feel welcome" earned/><Badge icon="✎" title="Story starter" detail="Share your first post"/><Badge icon="◉" title="Curious mind" detail="Explore 5 new communities"/></div><div className="trust-note"><CircleHelp size={17}/><span>Points and badges are currently for recognition. They cannot be exchanged for money or goods.</span></div></>}
    {page==='Wallet'&&<><PageTitle eyebrow="MONEY, WITH CLARITY" title="Wallet" desc="A clear view of your money related activity."/><div className="wallet-notice"><span><Wallet size={19}/></span><div><b>Payment services aren’t connected yet</b><p>When available, all payments will be handled through regulated providers. No money moves through this preview.</p></div></div><div className="wallet-balance"><div><span className="eyebrow">DEMO WALLET · NO REAL FUNDS</span><h2>GH₵0.00</h2><p>Your wallet will appear here when a provider is connected.</p></div><div className="wallet-actions"><Button disabled><ArrowDownLeft size={16}/> Add funds</Button><Button disabled><ArrowUpRight size={16}/> Send</Button></div></div><div className="section-title"><div><h2>Recent activity</h2><p>Your transaction history will live here.</p></div></div><Empty title="Nothing to show yet" detail="Transactions will appear here once payment services are connected."/></>}
    {page==='Settings'&&<><PageTitle eyebrow="MAKE ECOVIBES YOURS" title="Settings" desc="A few thoughtful controls make a big difference."/><div className="settings-section"><div className="section-title"><div><h2>Data & media</h2><p>Choose how EcoVibes uses your connection.</p></div><span className="setting-saver"><Zap size={14}/> {state.saver==='standard'?'Standard':state.saver==='saver'?'Data saver':'Extreme saver'}</span></div><div className="mode-options">{([{value:'standard',icon:Sun,title:'Standard',description:'Full images and gentle preloading.'},{value:'saver',icon:Zap,title:'Data saver',description:'Smaller previews. Video stays paused.'},{value:'extreme',icon:Download,title:'Extreme saver',description:'Text first. Images load when you ask.'}] as const).map(({value,icon:Icon,title,description})=><button className={`mode-option ${state.saver===value?'selected':''}`} onClick={()=>patch({saver:value})} key={value}><span className="mode-radio">{state.saver===value&&<i/>}</span><span className="mode-option-icon"><Icon size={17}/></span><span><b>{title}</b><small>{description}</small></span>{state.saver===value&&<Check size={17} className="mode-check"/>}</button>)}</div><p className="settings-hint"><Check size={14}/> Your choice is saved on this device and works across EcoVibes.</p></div><div className="settings-section"><div className="section-title"><div><h2>Appearance</h2><p>Comfortable in the day or after dark.</p></div></div><div className="mode-options">{(['light','dark'] as const).map(t=><button key={t} className={`mode-option ${state.theme===t?'selected':''}`} onClick={()=>patch({theme:t})}><span className="mode-radio">{state.theme===t&&<i/>}</span><span className="mode-option-icon">{t==='light'?<Sun size={17}/>:<Disc3 size={17}/>}</span><span><b>{t==='light'?'Light mode':'Dark mode'}</b><small>{t==='light'?'Soft, bright and easy to read.':'A softer look for the evening.'}</small></span></button>)}</div></div><div className="settings-section"><div className="section-title"><div><h2>Privacy & safety</h2><p>You’re in control of your EcoVibes experience.</p></div></div>{['Who can message me','Muted accounts','Blocked accounts','Download my data'].map(x=><button className="setting-row" onClick={()=>notify(`${x} settings`)} key={x}>{x}<ChevronRight size={17}/></button>)}</div></>}
   </main>
  </div>
  <nav className="mobile-nav" aria-label="Main navigation">{navItems.map(({page:p,icon:Icon,label})=><button key={p} onClick={()=>p==='Create'?setShowComposer(true):go(p)} className={page===p?'active':''}><Icon size={20}/><span>{label}</span>{p==='Create'&&<i/>}</button>)}</nav>
  <Sidekick onNavigate={destination=>go(destination)}/>
  {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
  {showComposer&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setShowComposer(false)}}><form className="composer-modal" onSubmit={submitPost}><div className="modal-head"><div><span className="eyebrow">YOUR COMMUNITY</span><h2>Share a moment</h2></div><button type="button" className="icon-button" onClick={()=>setShowComposer(false)} aria-label="Close"><X size={19}/></button></div><div className="composer-user"><Avatar label="PK"/><span><b>Philip K.</b><small>Posting to your community</small></span></div><textarea autoFocus placeholder="What’s on your mind?" value={state.draft} onChange={e=>patch({draft:e.target.value})} rows={5}/><div className="composer-footer"><span><Zap size={14}/> Draft saved on this device</span><Button kind="primary" disabled={!state.draft.trim()}>Share post <Send size={15}/></Button></div></form></div>}
  {cartOpen&&<div className="drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setCartOpen(false)}}><aside className="cart-drawer"><div className="drawer-head"><div><span className="eyebrow">THE ECOVIBES MARKETPLACE</span><h2>Your bag <span>{cartCount}</span></h2></div><button className="icon-button" aria-label="Close bag" onClick={()=>setCartOpen(false)}><X size={19}/></button></div>{cartCount===0?<Empty title="Your bag is taking a breather" detail="When something catches your eye, add it here."><Button kind="primary" onClick={()=>{setCartOpen(false);go('Marketplace')}}>Explore the marketplace <ChevronRight size={16}/></Button></Empty>:<><div className="cart-items">{catalogProducts.filter(p=>state.cart[p.id]).map(p=><div className="cart-item" key={p.id}><span className={`cart-thumb ${p.color}`}>{p.icon}</span><div><b>{p.name}</b><small>{p.seller} · Qty {state.cart[p.id]}</small><strong>{fmt(p.price*(state.cart[p.id]||0))}</strong></div><button aria-label={`Remove ${p.name}`} onClick={()=>{const c={...state.cart};delete c[p.id];patch({cart:c})}}><X size={16}/></button></div>)}</div><div className="cart-summary"><div><span>Subtotal</span><b>{fmt(total)}</b></div><small>Delivery and taxes are confirmed by the seller before a real order.</small><Button kind="primary" className="checkout-button" onClick={checkout}>Continue in sandbox <ChevronRight size={16}/></Button><p><CircleHelp size={13}/> This preview does not charge or create a real order.</p></div></>}</aside></div>}
 </div>
}
function ArrowHomeIcon(){return <span className="arrow-home-icon">↗</span>}
function PageTitle({eyebrow,title,desc,action}:{eyebrow:string;title:string;desc:string;action?:ReactNode}){return <div className="page-title-row"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="subhead">{desc}</p></div>{action}</div>}
function PostCard({post,liked,saved,onLike,onSave,onComment}:{post:FeedPost;liked:boolean;saved:boolean;onLike:()=>void;onSave:()=>void;onComment:()=>void}){return <article className="post-card"><div className="post-head"><Avatar label={post.avatar}/><div className="post-author"><b>{post.name}</b><small>@{post.handle} <span>·</span> {post.time}</small></div><span className="post-tag">{post.tag}</span><button className="post-more" aria-label="More post options"><MoreHorizontal size={18}/></button></div><p className="post-text">{post.text}</p>{post.art&&<button onClick={()=>{}} aria-label="Open post image" className={`post-art ${post.art}`}><span className="art-orb"/><span className="art-shape"/><span className="post-art-caption">MOMENTS<br/>IN MOTION</span><span className="post-art-foot">{post.tag==='CREATOR'?'AMA STUDIO · ACCRA':'COMMUNITY NOTES · VOL. 04'}</span></button>}<div className="post-actions"><button className={liked?'is-liked':''} onClick={onLike}><Heart size={17} fill={liked?'currentColor':'none'}/><span>{post.likes+(liked?1:0)}</span></button><button onClick={onComment}><MessageCircle size={17}/><span>{post.comments}</span></button><button onClick={()=>navigator.share?.({title:'EcoVibes',text:post.text}).catch(()=>{})}><ArrowUpRight size={17}/><span>Share</span></button><button className={`save-post ${saved?'is-saved':''}`} aria-label="Save post" onClick={onSave}><Bookmark size={17} fill={saved?'currentColor':'none'}/></button></div></article>}
function DiscoverCard({icon,label,title,detail,onClick}:{icon:ReactNode;label:string;title:string;detail:string;onClick:()=>void}){return <button className="discover-card" onClick={onClick}><span className="discover-icon">{icon}</span><span className="eyebrow">{label}</span><b>{title}</b><small>{detail}</small><ChevronRight size={16}/></button>}
function GameTile({title,type,colors,icon,onClick}:{title:string;type:string;colors:string;icon:string;onClick:()=>void}){return <button className="game-tile" onClick={onClick}><span className={`game-art ${colors}`}><span>{icon}</span><i/><b>PLAY</b></span><small>{type}</small><strong>{title}</strong><span className="game-tile-link">View game <ChevronRight size={14}/></span></button>}
function Badge({icon,title,detail,earned=false}:{icon:string;title:string;detail:string;earned?:boolean}){return <div className={`badge-card ${earned?'earned':''}`}><span className="badge-art">{icon}</span><b>{title}</b><small>{detail}</small><span className="badge-status">{earned?'EARNED':'IN PROGRESS'}</span></div>}
function Empty({title,detail,children}:{title:string;detail:string;children?:ReactNode}){return <div className="empty-state"><PatternBackdrop motif="adinkra" color="#a88755" intensity={.07} animated={false}/><GlowGrid intensity={.1} animated={false}/><span className="empty-mark"><Layers3 size={20}/></span><h3>{title}</h3><p>{detail}</p>{children}</div>}
export default App;
