import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { AudioConference, LiveKitRoom, RoomAudioRenderer, VideoConference } from '@livekit/components-react';
import '@livekit/components-styles';
import { Activity, Mic, Phone, Radio, Video, X } from 'lucide-react';

type MediaMode = 'voice' | 'video' | 'live';
type Session = { id:string; mode:MediaMode; title:string; visibility:'private'|'public'; status:string; created_at:string; creator_eco_id:string; creator_name:string; role?:string };
type JoinInfo = { token:string; serverUrl:string; session:{id:string;mode:MediaMode;title:string;role:string;canPublish:boolean} };
const api='/api/v1';
async function request<T>(path:string, csrf:string, init:RequestInit={}) {
  const response=await fetch(`${api}${path}`,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(init.method&&init.method!=='GET'?{'X-CSRF-Token':csrf}:{}),...init.headers}});
  const result=await response.json();
  if(!response.ok) throw new Error(result.error?.message||'The request could not be completed.');
  return result as T;
}
export default function Communications(){
  const [csrf,setCsrf]=useState(''); const [user,setUser]=useState<{id:string;display_name:string}|null>(null);
  const [configured,setConfigured]=useState(false); const [sessions,setSessions]=useState<Session[]>([]);
  const [mode,setMode]=useState<MediaMode>('video'); const [title,setTitle]=useState(''); const [invitees,setInvitees]=useState('');
  const [active,setActive]=useState<JoinInfo|null>(null); const [stream,setStream]=useState<{url:string;streamKey:string}|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const refresh=useCallback(async()=>{try{const [me,data]=await Promise.all([request<{user:{id:string;display_name:string}|null;csrfToken:string|null}>('/auth/me',''),request<{sessions:Session[];configured:boolean}>('/media/sessions',csrf)]);setUser(me.user);setCsrf(me.csrfToken||'');setSessions(data.sessions);setConfigured(data.configured);}catch(e){setError(e instanceof Error?e.message:'Could not load rooms.');}},[csrf]);
  useEffect(()=>{let done=false;Promise.all([fetch(`${api}/auth/me`,{credentials:'include'}).then(r=>r.json()),fetch(`${api}/media/status`,{credentials:'include'}).then(r=>r.json()),fetch(`${api}/media/sessions`,{credentials:'include'}).then(r=>r.json())]).then(([me,status,data])=>{if(done)return;setUser(me.user);setCsrf(me.csrfToken||'');setConfigured(Boolean(status.configured));setSessions(data.sessions||[]);}).catch(()=>{if(!done)setError('Start the EcoVibes API and sign in to use live rooms.');});return()=>{done=true;}},[]);
  async function create(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{const result=await request<{id:string}>('/media/sessions',csrf,{method:'POST',body:JSON.stringify({mode,title:title.trim()||undefined,visibility:mode==='live'?'public':'private',invitees:invitees.split(',').map(x=>x.trim()).filter(Boolean)})});await join(result.id);}catch(e){setError(e instanceof Error?e.message:'Could not create room.');}finally{setBusy(false);}}
  async function join(id:string){setError('');setBusy(true);try{const data=await request<JoinInfo>(`/media/sessions/${id}/join`,csrf,{method:'POST',body:'{}'});setActive(data);setStream(null);await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not join room.');}finally{setBusy(false);}}
  async function startStream(){if(!active)return;try{setStream(await request(`/media/sessions/${active.session.id}/ingress`,csrf,{method:'POST',body:'{}'}));}catch(e){setError(e instanceof Error?e.message:'Could not start stream ingest.');}}
  async function endRoom(){if(!active)return;try{await request(`/media/sessions/${active.session.id}/end`,csrf,{method:'POST',body:'{}'});setActive(null);setStream(null);await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not end room.');}}
  if(active)return <section className="media-page"><div className="media-room-head"><div><span className="eyebrow">{active.session.mode.toUpperCase()} ROOM · {active.session.role.toUpperCase()}</span><h1>{active.session.title}</h1></div><button className="media-button" onClick={()=>{setActive(null);setStream(null);refresh();}}><X size={17}/> Leave</button></div><LiveKitRoom token={active.token} serverUrl={active.serverUrl} connect audio={active.session.canPublish} video={active.session.mode==='video'&&active.session.canPublish} onDisconnected={()=>setActive(null)}>{active.session.mode==='voice'?<AudioConference/>:<VideoConference/>}<RoomAudioRenderer/></LiveKitRoom>{active.session.mode==='live'&&active.session.role==='host'&&<div className="media-stream-tools"><button className="media-button primary" onClick={startStream}><Radio size={16}/> Get OBS stream key</button>{stream&&<div><b>Server URL</b><code>{stream.url}</code><b>Stream key</b><code>{stream.streamKey}</code><small>Keep this key private. It is shown only while this room is open.</small></div>}</div>}<div className="media-room-actions"><span><Activity size={15}/> Connected with LiveKit</span>{active.session.role==='host'&&<button className="media-button danger" onClick={endRoom}><Phone size={16}/> End room for everyone</button>}</div></section>;
  return <section className="media-page"><header className="media-hero"><div><span className="eyebrow">REAL TIME, TOGETHER</span><h1>Calls & Live</h1><p>Start a private audio or video call, or go live with your community.</p></div><span className="media-hero-mark"><Activity size={29}/></span></header>
    {!user&&<div className="media-notice">Sign in with your EcoVibes ID to start or join rooms. <a href="#" onClick={e=>{e.preventDefault();window.dispatchEvent(new CustomEvent('ecovibes:navigate',{detail:'EcoVibes ID'}));}}>Open EcoVibes ID</a></div>}
    {!configured&&<div className="media-notice">The LiveKit integration is ready. Add <code>LIVEKIT_URL</code>, <code>LIVEKIT_API_KEY</code>, and <code>LIVEKIT_API_SECRET</code> to the API environment to enable real connections.</div>}
    {error&&<div className="media-error" role="alert">{error}</div>}
    <form className="media-create" onSubmit={create}><div className="media-section-title"><div><span className="eyebrow">START SOMETHING</span><h2>Open a room</h2></div><span className="media-live-dot">{configured?'PROVIDER READY':'SETUP NEEDED'}</span></div><label>Room name<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="A quick catch up" maxLength={100}/></label><div className="media-mode-pick">{([{value:'voice',label:'Voice call',icon:Mic},{value:'video',label:'Video call',icon:Video},{value:'live',label:'Go live',icon:Radio}] as const).map(({value,label,icon:Icon})=><button type="button" key={value} className={mode===value?'selected':''} onClick={()=>setMode(value)}><Icon size={18}/><span>{label}</span></button>)}</div>{mode!=='live'&&<label>Invite EcoVibes IDs <small>Comma separated · invitations appear in their notifications</small><input value={invitees} onChange={e=>setInvitees(e.target.value)} placeholder="ama, esi"/></label>}<button className="media-button primary" disabled={!configured||!user||busy}><Phone size={16}/>{busy?'Connecting…':mode==='live'?'Go live':'Start '+mode+' call'}</button></form>
    <div className="media-section-title media-discovery-title"><div><span className="eyebrow">COMMUNITY</span><h2>Live now</h2></div><button className="media-refresh" onClick={refresh}>Refresh</button></div>{sessions.filter(s=>s.mode==='live'&&s.visibility==='public').length===0?<div className="media-empty"><Radio size={20}/><b>No public live rooms right now</b><span>When someone goes live, you’ll find them here.</span></div>:<div className="media-session-list">{sessions.filter(s=>s.mode==='live'&&s.visibility==='public').map(s=><article key={s.id}><span className="media-live-dot">LIVE</span><div><b>{s.title}</b><small>@{s.creator_eco_id} · hosted by {s.creator_name}</small></div><button className="media-button primary" disabled={!configured||busy} onClick={()=>join(s.id)}>Join live</button></article>)}</div>}
    <div className="media-section-title media-discovery-title"><div><span className="eyebrow">YOUR ROOMS</span><h2>Invitations & active calls</h2></div></div>{sessions.filter(s=>s.mode!=='live'||s.visibility!=='public').length===0?<div className="media-empty"><Phone size={20}/><span>Your invitations and private rooms will appear here.</span></div>:<div className="media-session-list">{sessions.filter(s=>s.mode!=='live'||s.visibility!=='public').map(s=><article key={s.id}><span className="media-session-icon">{s.mode==='voice'?<Mic size={17}/>:<Video size={17}/>}</span><div><b>{s.title}</b><small>{s.mode} · {s.role||'invited'} · {s.creator_name}</small></div><button className="media-button" disabled={!configured||busy} onClick={()=>join(s.id)}>Join</button></article>)}</div>}
  </section>;
}
