import { useCallback, useEffect, useState, type ChangeEvent, type FormEvent } from 'react';
import { Eye, Film, Heart, ImagePlus, Plus, Sparkles, UserPlus, X } from 'lucide-react';
import { GlowGrid, PatternBackdrop } from './africa-art';
import { apiUrl } from '../lib/api';

type Story={id:string;author_id:string;text:string;asset_id:string|null;visibility:string;created_at:string;expires_at:string;eco_id:string;display_name:string;view_count:number;viewed:boolean};
type Reel={id:string;author_id:string;caption:string;asset_id:string;created_at:string;eco_id:string;display_name:string;view_count:number;like_count:number;viewed:boolean;liked:boolean;score:number};
type Person={id:string;eco_id:string;display_name:string;active:boolean;score:number;mutual_count:number;reasons:string[]};
async function apiCall<T>(path:string,csrf:string,init:RequestInit={}){const response=await fetch(apiUrl(path),{...init,credentials:'include',headers:{'Content-Type':'application/json',...(init.method&&init.method!=='GET'?{'X-CSRF-Token':csrf}:{}),...init.headers}});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||'Could not complete the request.');return data as T;}
async function fileData(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(new Error('Could not read this file.'));reader.readAsDataURL(file);});}
async function upload(file:File,csrf:string){if(file.size>14*1024*1024)throw new Error('Choose a file smaller than 14 MB.');const result=await apiCall<{id:string}>('/social/assets',csrf,{method:'POST',body:JSON.stringify({mimeType:file.type,data:await fileData(file)})});return result.id;}
function AssetImage({assetId,alt}:{assetId:string;alt:string}){const [src,setSrc]=useState('');useEffect(()=>{const controller=new AbortController();let objectUrl='';void fetch(apiUrl('/social/assets/'+assetId),{credentials:'include',signal:controller.signal}).then(response=>{if(!response.ok)throw new Error('Media unavailable');return response.blob();}).then(blob=>{objectUrl=URL.createObjectURL(blob);setSrc(objectUrl);}).catch(()=>setSrc(''));return()=>{controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[assetId]);return <img src={src||undefined} alt={alt}/>;}
function useSocialSession(){const [user,setUser]=useState<{id:string;csrfToken:string|null}|null>(null);const [ready,setReady]=useState(false);useEffect(()=>{apiCall<{user:{id:string}|null;csrfToken:string|null}>('/auth/me','').then(me=>setUser(me.user?{id:me.user.id,csrfToken:me.csrfToken}:null)).catch(()=>setUser(null)).finally(()=>setReady(true));},[]);return {user,csrf:user?.csrfToken||'',ready};}
export function StoriesStrip({onSignIn}:{onSignIn:()=>void}){const {user,csrf,ready}=useSocialSession();const [stories,setStories]=useState<Story[]>([]);const [selected,setSelected]=useState<Story|null>(null);const [compose,setCompose]=useState(false);const [text,setText]=useState('');const [file,setFile]=useState<File|null>(null);const [visibility,setVisibility]=useState<'public'|'followers'>('public');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const refresh=useCallback(async()=>{if(!user)return;try{setStories((await apiCall<{stories:Story[]}>('/stories',csrf)).stories);}catch(e){setError(e instanceof Error?e.message:'Could not load Stories.');}},[csrf,user]);useEffect(()=>{void refresh();},[refresh]);
 async function post(e:FormEvent){e.preventDefault();if(!user){onSignIn();return;}setBusy(true);setError('');try{const assetId=file?await upload(file,csrf):undefined;await apiCall('/stories',csrf,{method:'POST',body:JSON.stringify({text,assetId,visibility})});setText('');setFile(null);setCompose(false);await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not post your status.');}finally{setBusy(false);}}
 async function open(story:Story){setSelected(story);if(user&&!story.viewed)try{await apiCall(`/stories/${story.id}/view`,csrf,{method:'POST',body:'{}'});setStories(list=>list.map(item=>item.id===story.id?{...item,viewed:true,view_count:item.view_count+1}:item));}catch{/* The Story remains viewable if a view marker cannot be saved. */}}
 return <><section className="social-stories"><PatternBackdrop motif="weave" color="#9f8658" intensity={.055} animated={false}/><GlowGrid color="#78a76d" intensity={.09} animated={false}/><div className="social-strip-heading"><div><span className="eyebrow">YOUR PEOPLE</span><h2>Stories <small>24 hours</small></h2></div>{error&&<span className="social-inline-error">{error}</span>}</div><div className="story-bubbles"><button className="story-bubble story-add" onClick={()=>user?setCompose(true):onSignIn()}><span className="story-ring own"><i><Plus size={22}/></i></span><b>Your status</b><small>Share a moment</small></button>{stories.map(story=><button key={story.id} className="story-bubble" onClick={()=>void open(story)}><span className={`story-ring ${story.viewed?'seen':''}`}>{story.asset_id?<AssetImage assetId={story.asset_id} alt=""/>:<i>{story.display_name.slice(0,1).toUpperCase()}</i>}</span><b>{story.display_name.split(' ')[0]}</b><small>{story.view_count} views</small></button>)}{ready&&!user&&<button className="story-signin" onClick={onSignIn}>Sign in to see your community’s Stories</button>}</div></section>
 {compose&&<div className="social-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setCompose(false)}}><form className="social-composer" onSubmit={post}><header><div><span className="eyebrow">YOUR STATUS · EXPIRES IN 24 HOURS</span><h2>Share a Story</h2></div><button type="button" className="social-icon-button" onClick={()=>setCompose(false)}><X size={18}/></button></header><textarea value={text} onChange={e=>setText(e.target.value)} maxLength={500} placeholder="What’s happening?"/><select className="story-visibility" value={visibility} onChange={e=>setVisibility(e.target.value as 'public'|'followers')}><option value="public">Everyone can see this Story</option><option value="followers">Only people who follow you</option></select><label className="social-file-pick"><ImagePlus size={17}/>{file?file.name:'Add a photo'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e:ChangeEvent<HTMLInputElement>)=>setFile(e.target.files?.[0]||null)}/></label><button className="social-primary" disabled={busy||(!text.trim()&&!file)}>{busy?'Posting…':'Post status'}</button>{error&&<p className="social-inline-error">{error}</p>}</form></div>}
 {selected&&<div className="social-overlay story-viewer" onClick={()=>setSelected(null)}><article onClick={e=>e.stopPropagation()}><button className="social-icon-button viewer-close" onClick={()=>setSelected(null)}><X size={19}/></button>{selected.asset_id&&<AssetImage assetId={selected.asset_id} alt="Story shared by community member"/>}<div><small>@{selected.eco_id}</small><h2>{selected.display_name}</h2>{selected.text&&<p>{selected.text}</p>}<span><Eye size={14}/> {selected.view_count} views</span></div></article></div>}</>;
}
export function PeopleToFollow({onSignIn}:{onSignIn:()=>void}){const {user,csrf}=useSocialSession();const [people,setPeople]=useState<Person[]>([]);const [error,setError]=useState('');const refresh=useCallback(async()=>{if(!user)return;try{setPeople((await apiCall<{people:Person[]}>('/people/discover',csrf)).people);}catch(e){setError(e instanceof Error?e.message:'Suggestions are unavailable.');}},[csrf,user]);useEffect(()=>{void refresh();},[refresh]);async function follow(person:Person){try{await apiCall(`/people/${person.id}/follow`,csrf,{method:'POST',body:'{}'});setPeople(list=>list.filter(item=>item.id!==person.id));}catch(e){setError(e instanceof Error?e.message:'Could not follow this person.');}}
 return <div className="rail-card creator-card"><div className="rail-heading"><h3><Sparkles size={15}/> Active people</h3><button onClick={()=>user?void refresh():onSignIn()} className="text-link">Refresh</button></div>{people.length?people.slice(0,4).map(person=><div className="social-person" key={person.id}><span className={`social-person-avatar ${person.active?'online':''}`}>{person.display_name.slice(0,1).toUpperCase()}</span><span><b>{person.display_name}</b><small>@{person.eco_id} · {person.reasons[0]||'In the community'}</small></span><button title="Follow" aria-label={`Follow ${person.display_name}`} onClick={()=>void follow(person)}><UserPlus size={15}/></button></div>):<div className="social-empty-people">{user?error||'New people will appear as they join and share.':<button onClick={onSignIn}>Sign in to find active people</button>}</div>}</div>;
}
export function ReelsPage({onSignIn}:{onSignIn:()=>void}){const {user,csrf,ready}=useSocialSession();const [reels,setReels]=useState<Reel[]>([]);const [caption,setCaption]=useState('');const [file,setFile]=useState<File|null>(null);const [compose,setCompose]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const refresh=useCallback(async()=>{if(!user)return;try{setReels((await apiCall<{reels:Reel[]}>('/reels',csrf)).reels);}catch(e){setError(e instanceof Error?e.message:'Could not load Reels.');}},[csrf,user]);useEffect(()=>{void refresh();},[refresh]);
 async function post(e:FormEvent){e.preventDefault();if(!user){onSignIn();return;}if(!file)return;setBusy(true);setError('');try{const assetId=await upload(file,csrf);await apiCall('/reels',csrf,{method:'POST',body:JSON.stringify({assetId,caption})});setFile(null);setCaption('');setCompose(false);await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not post your Reel.');}finally{setBusy(false);}}
 async function like(reel:Reel){try{const result=await apiCall<{liked:boolean}>(`/reels/${reel.id}/like`,csrf,{method:'POST',body:'{}'});setReels(list=>list.map(item=>item.id===reel.id?{...item,like_count:item.like_count+(result.liked?1:-1)}:item));}catch(e){setError(e instanceof Error?e.message:'Could not like this Reel.');}}
 return <section className="reels-page"><header className="reels-header"><div><span className="eyebrow">SHORT VIDEOS · MADE BY YOUR COMMUNITY</span><h1>Reels</h1><p>Fresh videos from creators and people you follow.</p></div><button className="social-primary reel-post-button" onClick={()=>user?setCompose(true):onSignIn()}><Plus size={16}/> Post a Reel</button></header>{error&&<div className="social-inline-error">{error}</div>}{!user&&ready&&<div className="social-feed-empty">Sign in with EcoVibes ID to watch and post community Reels.<button onClick={onSignIn}>Open EcoVibes ID</button></div>}{user&&reels.length===0&&<div className="social-feed-empty"><Film size={24}/><b>Your Reels feed is ready</b><span>Post a short video to start the conversation.</span><button onClick={()=>setCompose(true)}>Post the first Reel</button></div>}{reels.length>0&&<div className="reels-grid">{reels.map(reel=><article className="reel-card" key={reel.id}><video src={apiUrl('/social/assets/'+reel.asset_id)} controls playsInline preload="metadata" onPlay={()=>{if(!reel.viewed){setReels(list=>list.map(item=>item.id===reel.id?{...item,viewed:true,view_count:item.view_count+1}:item));void apiCall(`/reels/${reel.id}/view`,csrf,{method:'POST',body:'{}'}).catch(()=>undefined);}}}/><div className="reel-details"><div><b>{reel.display_name}</b><small>@{reel.eco_id} · {reel.score} discovery</small></div><button className={`reel-like ${reel.liked?'liked':''}`} onClick={()=>void like(reel)}><Heart size={16} fill={reel.liked?'currentColor':'none'}/>{reel.like_count}</button></div>{reel.caption&&<p>{reel.caption}</p>}<small className="reel-views"><Eye size={13}/>{reel.view_count} views</small></article>)}</div>}
 {compose&&<div className="social-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setCompose(false)}}><form className="social-composer" onSubmit={post}><header><div><span className="eyebrow">YOUR COMMUNITY VIDEO</span><h2>Create a Reel</h2></div><button type="button" className="social-icon-button" onClick={()=>setCompose(false)}><X size={18}/></button></header><label className="social-video-pick"><Film size={19}/><b>{file?file.name:'Choose a video'}</b><small>MP4 or WebM · up to 14 MB</small><input type="file" accept="video/mp4,video/webm" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><textarea value={caption} onChange={e=>setCaption(e.target.value)} maxLength={500} placeholder="Add a caption…"/><button className="social-primary" disabled={busy||!file}>{busy?'Uploading…':'Post Reel'}</button>{error&&<p className="social-inline-error">{error}</p>}</form></div>}</section>;
}
