import { useState, type FormEvent } from 'react';
import { ArrowRight, BriefcaseBusiness, Check, CircleHelp, Clock3, MapPin, Plus, ShieldAlert, Users, Wallet, X } from 'lucide-react';
import { formatGhs } from './domain';
import { serviceCategories, type CustomJob, type CustomJobStatus, type HandiProfile, type JobOffer, type ProviderType, type ServiceCategory } from './model';

const labels:Record<CustomJobStatus,string>={open:'Open for offers',assigned:'Offer selected',in_progress:'In progress',awaiting_customer:'Confirm completion',completed:'Completed',cancelled:'Cancelled',disputed:'Under review'};
const typeLabels:Record<ProviderType,string>={individual:'Individual Handi',business:'Small business',company:'Company',team:'Team'};
export type NewJobInput={category:ServiceCategory;title:string;details:string;area:string;budgetMinor:number;timing:'asap'|'scheduled';scheduledAt?:string};
export type NewOfferInput={amountMinor:number;note:string;eta:string};
export default function JobsBoard({mode,currentEcoId,profile,jobs,onCreate,onOffer,onSelect,onMove}:{mode:'customer'|'handi';currentEcoId:string;currentName:string;profile?:HandiProfile;jobs:CustomJob[];onCreate:(input:NewJobInput)=>void;onOffer:(job:CustomJob,input:NewOfferInput)=>void;onSelect:(job:CustomJob,offer:JobOffer)=>void;onMove:(job:CustomJob,next:CustomJobStatus)=>void}){
 const [showPost,setShowPost]=useState(false);
 const [offerJob,setOfferJob]=useState<string|null>(null);
 const [amount,setAmount]=useState('');
 const [offerNote,setOfferNote]=useState('');
 const [eta,setEta]=useState('');
 const [toast,setToast]=useState('');
 function postJob(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const input:NewJobInput={category:String(data.get('category')) as ServiceCategory,title:String(data.get('title')||''),details:String(data.get('details')||''),area:String(data.get('area')||''),budgetMinor:Math.round(Number(data.get('budget'))*100),timing:String(data.get('timing')) as 'asap'|'scheduled',scheduledAt:String(data.get('scheduledAt')||'')};try{onCreate(input);setShowPost(false);setToast('Custom job posted on this device.');}catch(error){setToast(error instanceof Error?error.message:'Could not post this job.');}}
 function submitOffer(event:FormEvent<HTMLFormElement>,job:CustomJob){event.preventDefault();try{onOffer(job,{amountMinor:Math.round(Number(amount)*100),note:offerNote,eta});setOfferJob(null);setAmount('');setOfferNote('');setEta('');setToast('Offer saved on this device.');}catch(error){setToast(error instanceof Error?error.message:'Could not send offer.');}}
 const sorted=jobs.slice().sort((a,b)=>Number(b.ownerEcoId===currentEcoId)-Number(a.ownerEcoId===currentEcoId)||b.createdAt.localeCompare(a.createdAt));
 return <section className="qh-jobs-board"><div className="qh-jobs-intro"><div className="qh-jobs-intro-icon"><BriefcaseBusiness size={20}/></div><div><span className="eyebrow">CUSTOM JOBS · OFFERS</span><h2>Post the task. Compare the offers.</h2><p>For errands and one-off work that needs a custom plan and budget.</p></div><div className="qh-jobs-intro-art" aria-hidden="true"><span/><i/><b/></div></div><div className="qh-jobs-heading"><div><h3>{mode==='handi'?'Find work that fits':'Open jobs and your posts'}</h3><p>{mode==='handi'?'Send a clear offer with price and timing.':'Choose an offer after comparing its terms.'}</p></div>{mode==='customer'&&<button className="qh-primary-action" onClick={()=>setShowPost(true)}><Plus size={14}/> Post a job</button>}</div>
 {mode==='handi'&&!profile&&<div className="qh-board-message"><Users size={15}/> Create a Handi or team profile before you send offers.</div>}
 {sorted.length?<div className="qh-custom-jobs">{sorted.map(job=>{const isOwner=job.ownerEcoId===currentEcoId;const myOffer=job.offers.find(offer=>offer.providerEcoId===currentEcoId&&offer.status!=='declined');const winningOffer=job.offers.find(offer=>offer.status==='selected');return <article className="qh-custom-job" key={job.id}><header><div className="qh-job-icon"><BriefcaseBusiness size={17}/></div><span className="qh-custom-job-head"><small>{job.id} · {job.category.toUpperCase()} {job.sample&&<b>SAMPLE</b>}</small><strong>{job.title}</strong><i>Posted by {job.ownerName} · {job.area} · {job.timing==='asap'?'As soon as possible':job.scheduledAt||'Scheduled'}</i></span><span className={`qh-job-status ${job.status==='completed'?'done':job.status==='in_progress'||job.status==='awaiting_customer'?'working':job.status==='cancelled'||job.status==='disputed'?'muted':'pending'}`}>{labels[job.status]}</span></header><p className="qh-custom-job-details">{job.details}</p><div className="qh-custom-job-facts"><span><b>Budget</b><strong>{formatGhs(job.budgetMinor)}</strong><small>{job.sample?'Example budget':'Set by job owner'}</small></span><span><b>Offers</b><strong>{job.offers.filter(offer=>offer.status!=='declined').length}</strong><small>Compare price & timing</small></span><span><b>Service area</b><strong>{job.area}</strong><small>Exact address stays private</small></span></div>
 {job.offers.length>0&&<div className="qh-offers"><div className="qh-offers-heading"><h4>{isOwner?'Offers for your job':'Offer comparison'}</h4><small>{job.sample?'Sample offers for this preview':'Provider offers'}</small></div>{job.offers.map(offer=><div className={`qh-offer ${offer.status==='selected'?'selected':offer.status==='declined'?'declined':''}`} key={offer.id}><span className="qh-offer-avatar">{offer.providerName.split(' ').map(part=>part[0]).join('').slice(0,2)}</span><span className="qh-offer-main"><b>{offer.providerName}</b><small>{typeLabels[offer.providerType]} · {offer.providerEcoId}</small><i>{offer.note}</i></span><span className="qh-offer-terms"><b>{formatGhs(offer.amountMinor)}</b><small><Clock3 size={11}/>{offer.eta}</small></span>{isOwner&&job.status==='open'&&offer.status==='pending'&&<button className="qh-outline-action" onClick={()=>onSelect(job,offer)}>Choose offer <Check size={13}/></button>}{offer.status==='selected'&&<span className="qh-offer-selected">Selected</span>}</div>)}</div>}
 {job.status==='open'&&mode==='handi'&&profile&&!isOwner&&(myOffer?<div className="qh-board-message"><Check size={14}/> Your offer is in the comparison list at {formatGhs(myOffer.amountMinor)}.</div>:offerJob===job.id?<form className="qh-offer-form" onSubmit={event=>submitOffer(event,job)}><div><b>Make an offer</b><button type="button" onClick={()=>setOfferJob(null)} aria-label="Close offer form"><X size={14}/></button></div><div className="qh-offer-inputs"><label>Amount · GHS<input type="number" min="1" step="0.01" required value={amount} onChange={event=>setAmount(event.target.value)} placeholder="Offer amount"/></label><label>Estimated timing<input required maxLength={60} value={eta} onChange={event=>setEta(event.target.value)} placeholder="e.g. About 45 minutes"/></label></div><label>What’s included<textarea required maxLength={240} value={offerNote} onChange={event=>setOfferNote(event.target.value)} placeholder="Say what you’ll do and any important terms." rows={2}/></label><small>Use the in-app job chat for details. No payment is collected here.</small><button className="qh-primary-action">Send offer <ArrowRight size={14}/></button></form>:<button className="qh-primary-action qh-make-offer" onClick={()=>setOfferJob(job.id)}>Make an offer <ArrowRight size={14}/></button>)}
 {mode==='handi'&&job.status==='assigned'&&winningOffer?.providerEcoId===currentEcoId&&<div className="qh-job-actions"><button className="qh-primary-action" onClick={()=>onMove(job,'in_progress')}>Start job <ArrowRight size={14}/></button></div>}{mode==='handi'&&job.status==='in_progress'&&winningOffer?.providerEcoId===currentEcoId&&<div className="qh-job-actions"><button className="qh-primary-action" onClick={()=>onMove(job,'awaiting_customer')}>Mark finished <Check size={14}/></button></div>}{mode==='customer'&&isOwner&&job.status==='awaiting_customer'&&<div className="qh-job-actions"><button className="qh-primary-action" onClick={()=>onMove(job,'completed')}>Confirm completion <Check size={14}/></button><button className="qh-outline-action" onClick={()=>onMove(job,'disputed')}>Report a problem</button></div>}{mode==='customer'&&isOwner&&job.status==='assigned'&&<p className="qh-board-message"><Wallet size={14}/> Offer selected. Payment and escrow are not connected.</p>}
 {job.sample&&<p className="qh-sample-notice"><ShieldAlert size={13}/> Example job and offer. No request was sent and no provider has been contacted.</p>}</article>})}</div>:<div className="qh-empty qh-empty-compact"><span><BriefcaseBusiness size={19}/></span><h3>No open custom jobs</h3><p>Post a task with your budget, or check back when jobs are available in your area.</p></div>}
 <div className="qh-jobs-trust"><ShieldAlert size={14}/><span>Job budgets are proposed amounts. Agree scope and final price in writing before booking. This preview does not collect money or verify providers.</span></div>
 {toast&&<div className="qh-toast" role="status"><Check size={14}/>{toast}</div>}
 {showPost&&<div className="qh-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setShowPost(false)}}><form className="qh-modal" onSubmit={postJob}><div className="qh-modal-head"><div><span className="eyebrow">QUICK&HANDI · CUSTOM JOB</span><h2>What needs doing?</h2><p>Describe a one-off task and set your budget. Handis can send offers.</p></div><button type="button" onClick={()=>setShowPost(false)} aria-label="Close job form"><X size={18}/></button></div><label>Job title<input name="title" maxLength={90} required placeholder="e.g. Buy something at Circle and bring it to me"/></label><label>Details<textarea name="details" maxLength={700} rows={3} required placeholder="Describe the item, pickup details and what a successful job looks like."/></label><div className="qh-form-row"><label>Category<select name="category" defaultValue="Delivery & Errands">{serviceCategories.map(category=><option key={category}>{category}</option>)}</select></label><label>Service area<input name="area" maxLength={100} required placeholder="Neighbourhood, town or area"/></label></div><div className="qh-form-row"><label>Budget · GHS<input name="budget" type="number" min="1" step="0.01" required placeholder="Your proposed budget"/></label><label>When do you need it?<select name="timing" defaultValue="asap"><option value="asap">As soon as possible</option><option value="scheduled">Schedule for later</option></select></label></div><label>Preferred date and time (optional)<input type="datetime-local" name="scheduledAt"/></label><p className="qh-form-disclaimer"><CircleHelp size={14}/> Your area is shown to Handis. Add exact address after agreeing to a provider.</p><div className="qh-modal-foot"><p><MapPin size={14}/>Local preview · GHS budget</p><button className="qh-primary-action">Post custom job <ArrowRight size={14}/></button></div></form></div>}
 </section>;
}
