import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, BadgeCheck, BriefcaseBusiness, CalendarClock, Check, ChevronDown, CircleHelp, Clock3, MapPin, MessageCircle, Plus, Search, ShieldAlert, Star, Users, Wrench, X, Zap } from 'lucide-react';
import { createCustomJob, createServiceRequest, formatGhs, handiDirectory, initialQuickHandiState, matchHandis, saveQuote, selectJobOffer, submitCustomJobOffer, transitionCustomJob, transitionJob } from './domain';
import JobsBoard, { type NewJobInput, type NewOfferInput } from './JobsBoard';
import { serviceCategories, type CustomJob, type CustomJobStatus, type HandiProfile, type JobOffer, type JobStatus, type ProviderType, type QuickHandiState, type ServiceCategory, type ServiceRequest } from './model';

const STORE='ecovibes:quickhandi:v1';
function loadQuickState():QuickHandiState{const initial=initialQuickHandiState();try{const saved=JSON.parse(localStorage.getItem(STORE)||'{}');return {...initial,...saved,customJobs:saved.customJobs||initial.customJobs,categories:saved.categories||initial.categories};}catch{return initial;}}
const statusLabels:Record<JobStatus,string>={requested:'Request sent',quoted:'Quote received',accepted:'Accepted',confirmed:'Booking confirmed',in_progress:'In progress',awaiting_customer:'Confirm completion',completed:'Completed',cancelled:'Cancelled',disputed:'Under review'};
const areas=['Anywhere in Accra','Osu','East Legon','Adenta','Tema','Madina','Labone','Cape Coast'];
const statusTone=(status:JobStatus)=>['completed'].includes(status)?'done':['cancelled','disputed'].includes(status)?'muted':['in_progress','awaiting_customer'].includes(status)?'working':'pending';

export default function QuickHandi(){
 const [store,setStore]=useState<QuickHandiState>(loadQuickState);
 const [experience,setExperience]=useState<'services'|'jobs'>('services');
 const [query,setQuery]=useState('');
 const [area,setArea]=useState('Anywhere in Accra');
 const [category,setCategory]=useState<ServiceCategory|'All'>('All');
 const [requestFor,setRequestFor]=useState<HandiProfile|null>(null);
 const [expanded,setExpanded]=useState<string|null>(null);
 const [activeJob,setActiveJob]=useState<string|null>(null);
 const [toast,setToast]=useState('');
 const [becomeHandi,setBecomeHandi]=useState(false);
 const [quote,setQuote]=useState('');
 const [quoteNote,setQuoteNote]=useState('');
 const [chatText,setChatText]=useState('');
 const [reviewText,setReviewText]=useState('');
 const [rating,setRating]=useState(5);
 useEffect(()=>{try{localStorage.setItem(STORE,JSON.stringify(store));}catch{/* Keep this feature usable when browser storage is unavailable. */}},[store]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(id)},[toast]);
 const profiles=useMemo(()=>store.ownProfile?[store.ownProfile,...handiDirectory]:handiDirectory,[store.ownProfile]);
 const matches=useMemo(()=>matchHandis(profiles,query,category,area),[profiles,query,category,area]);
 const setMode=(mode:QuickHandiState['mode'])=>setStore(current=>({...current,mode}));
 const updateJob=(id:string,transform:(job:ServiceRequest)=>ServiceRequest)=>setStore(current=>({...current,requests:current.requests.map(job=>job.id===id?transform(job):job)}));
 function createJob(input:NewJobInput){const job=createCustomJob({ownerEcoId:'@philipk',ownerName:'Philip K.',...input});setStore(current=>({...current,customJobs:[job,...current.customJobs]}));}
 function addJobOffer(job:CustomJob,input:NewOfferInput){if(!store.ownProfile)throw new Error('Create a Handi profile to make an offer.');const updated=submitCustomJobOffer(job,{...input,providerId:store.ownProfile.id,providerEcoId:store.ownProfile.ecoId,providerName:store.ownProfile.businessName||store.ownProfile.name,providerType:store.ownProfile.providerType||'individual'});setStore(current=>({...current,customJobs:current.customJobs.map(item=>item.id===job.id?updated:item)}));}
 function chooseJobOffer(job:CustomJob,offer:JobOffer){const updated=selectJobOffer(job,offer.id,'@philipk');setStore(current=>({...current,customJobs:current.customJobs.map(item=>item.id===job.id?updated:item)}));}
 function moveCustomJob(job:CustomJob,next:CustomJobStatus){const updated=transitionCustomJob(job,next,store.mode==='handi'?(store.ownProfile?.ecoId||'@philipk'):'@philipk');setStore(current=>({...current,customJobs:current.customJobs.map(item=>item.id===job.id?updated:item)}));}
 function moveJob(job:ServiceRequest,next:JobStatus){try{updateJob(job.id,current=>transitionJob(current,next));setToast(next==='completed'?'Completion confirmed. Leave a review when you’re ready.':`Request updated · ${statusLabels[next]}`);}catch(error){setToast(error instanceof Error?error.message:'Could not update request.');}}
 function submitRequest(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!requestFor)return;const data=new FormData(event.currentTarget);const title=String(data.get('title')||'').trim();const details=String(data.get('details')||'').trim();const requestArea=String(data.get('area')||'').trim();const timing=String(data.get('timing')) as 'asap'|'scheduled';const scheduledAt=String(data.get('scheduledAt')||'');if(!title||!details||!requestArea){setToast('Add a short title, job details and service area.');return}const request=createServiceRequest({provider:requestFor,category:requestFor.category,title,details,area:requestArea,timing,scheduledAt});setStore(current=>({...current,requests:[request,...current.requests]}));setRequestFor(null);setActiveJob(request.id);setToast(`Request ${request.id} saved on this device.`);}
 function submitProvider(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const name=String(data.get('name')||'').trim();const service=String(data.get('service')||'').trim();const profileArea=String(data.get('area')||'').trim();const categoryValue=String(data.get('category')) as ServiceCategory;const price=Number(data.get('price'));if(!name||!service||!profileArea||!Number.isFinite(price)||price<1){setToast('Complete each profile field with a valid indicative price.');return}const profile:HandiProfile={id:`handi-${crypto.randomUUID?.()||Date.now()}`,ecoId:'@philipk',name,providerType:String(data.get('providerType')) as ProviderType,teamSize:Number(data.get('teamSize'))||undefined,category:categoryValue,services:[service],area:profileArea,serviceRadiusKm:10,bio:'Local preview profile. Add more details when provider accounts are connected.',estimateMinor:Math.round(price*100),pricing:String(data.get('pricing')) as HandiProfile['pricing'],availability:'Availability set by you',responseTime:'Response time not yet available',reviewCount:0,completedJobs:0,verification:'unverified',sample:false};setStore(current=>({...current,ownProfile:profile,mode:'handi'}));setBecomeHandi(false);setToast('Handi profile saved on this device.');}
 function submitQuote(event:FormEvent<HTMLFormElement>,job:ServiceRequest){event.preventDefault();const amount=Math.round(Number(quote)*100);try{updateJob(job.id,current=>saveQuote(current,amount,quoteNote));setQuote('');setQuoteNote('');setToast('Sample quote attached. No payment was taken.');}catch(error){setToast(error instanceof Error?error.message:'Quote could not be saved.');}}
 function sendJobMessage(event:FormEvent<HTMLFormElement>,job:ServiceRequest){event.preventDefault();const text=chatText.trim();if(!text)return;updateJob(job.id,current=>({...current,messages:[...current.messages,{id:`chat-${Date.now()}`,sender:store.mode==='handi'?'handi':'customer',text,at:new Date().toISOString()}]}));setChatText('');}
 function submitReview(event:FormEvent<HTMLFormElement>,job:ServiceRequest){event.preventDefault();if(!reviewText.trim()){setToast('Add a short note with your rating.');return}updateJob(job.id,current=>({...current,rating,review:reviewText.trim()}));setReviewText('');setToast('Review saved locally. It is not published.');}
 const visibleCategories=store.categories.filter(item=>!query||item.toLowerCase().includes(query.toLowerCase()));
 return <div className="qh-page">
  <div className="qh-heading"><div><span className="eyebrow">ECOVIBES · GET THINGS DONE</span><h1>Quick<span>&</span>Handi</h1><p>Need something done? Find someone who can do it.</p></div><button className="qh-mode-toggle" onClick={()=>store.ownProfile?setMode(store.mode==='customer'?'handi':'customer'):setBecomeHandi(true)}><span className={store.mode==='handi'?'mode-active':''}>{store.mode==='handi'?'Handi mode':'Customer mode'}</span><ChevronDown size={15}/></button></div>
  <div className="qh-trust-strip"><Zap size={15}/><span>Low-data service discovery</span><i/><span>Location shared by area only</span><i/><span>GHS · Ghana preview</span></div>
  {store.mode==='customer'?<>
   <section className="qh-hero"><div className="qh-hero-copy"><span className="eyebrow">LOCAL SERVICES, ONE ECOVIBES ID</span><h2>More time for<br/><em>what matters.</em></h2><p>Find a trusted local professional for the jobs you need done.</p><button onClick={()=>document.getElementById('qh-find')?.scrollIntoView({behavior:'smooth',block:'start'})}>Find a service <ArrowRight size={16}/></button></div><div className="qh-hero-scene" aria-hidden="true"><span className="qh-scene-orbit scene-one"/><span className="qh-scene-orbit scene-two"/><span className="qh-scene-orbit scene-three"/><span className="qh-scene-center"><Wrench size={28}/></span><span className="qh-scene-chip scene-chip-one">HOME</span><span className="qh-scene-chip scene-chip-two">CREATIVE</span><span className="qh-scene-chip scene-chip-three">EVERYDAY</span></div></section>
   <div className="qh-experience-tabs"><button className={experience==='services'?'selected':''} onClick={()=>setExperience('services')}><Wrench size={15}/> Find a service <small>Browse listed Handis</small></button><button className={experience==='jobs'?'selected':''} onClick={()=>setExperience('jobs')}><BriefcaseBusiness size={15}/> Custom jobs <small>Post a task and compare offers</small></button></div>
   {experience==='services'?<>
   <section className="qh-search-section" id="qh-find"><div className="qh-section-head"><div><span className="eyebrow">YOUR LOCAL SERVICE GUIDE</span><h2>What do you need help with?</h2></div><span className="qh-result-count">{matches.length} sample {matches.length===1?'Handi':'Handis'}</span></div><div className="qh-search-fields"><label className="qh-search-box"><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Try plumbing, a delivery, a photoshoot…" aria-label="Search a service"/><kbd>SEARCH</kbd></label><label className="qh-area-box"><MapPin size={16}/><select value={area} onChange={event=>setArea(event.target.value)} aria-label="Choose a service area">{areas.map(item=><option key={item}>{item}</option>)}</select><ChevronDown size={14}/></label></div>
    <div className="qh-categories" aria-label="Service categories"><button className={category==='All'?'chosen':''} onClick={()=>setCategory('All')}>All services</button>{visibleCategories.slice(0,9).map(item=><button className={category===item?'chosen':''} onClick={()=>setCategory(item)} key={item}>{item}</button>)}{visibleCategories.length>9&&<select aria-label="More service categories" value={category==='All'||visibleCategories.slice(0,9).includes(category)?'':category} onChange={event=>setCategory(event.target.value as ServiceCategory)}><option value="">More services</option>{visibleCategories.slice(9).map(item=><option key={item}>{item}</option>)}</select>}</div>
   </section>
   <div className="qh-list-heading"><div><h2>Handis around {area==='Anywhere in Accra'?'Accra':area}</h2><p>Compare service details and decide who to contact.</p></div><button onClick={()=>setBecomeHandi(true)}>Become a Handi <Plus size={15}/></button></div>
   {matches.length?<div className="qh-provider-grid">{matches.map(profile=><ProviderCard key={profile.id} profile={profile} expanded={expanded===profile.id} onExpand={()=>setExpanded(expanded===profile.id?null:profile.id)} onRequest={()=>setRequestFor(profile)}/>)}</div>:<div className="qh-empty"><span><Search size={20}/></span><h3>No matching Handis in this preview</h3><p>Try another category or area. More Ghana locations can be added as providers join.</p><button onClick={()=>{setCategory('All');setArea('Anywhere in Accra');setQuery('')}}>Clear filters</button></div>}
   <div className="qh-job-list"><div className="qh-list-heading"><div><h2>Your service requests</h2><p>Track status, chat and confirm the work.</p></div><span className="qh-result-count">{store.requests.length} saved here</span></div>{store.requests.length?store.requests.slice().reverse().map(job=><JobCard key={job.id} job={job} mode={store.mode} expanded={activeJob===job.id} quote={quote} quoteNote={quoteNote} setQuote={setQuote} setQuoteNote={setQuoteNote} chatText={chatText} setChatText={setChatText} reviewText={reviewText} setReviewText={setReviewText} rating={rating} setRating={setRating} onToggle={()=>setActiveJob(activeJob===job.id?null:job.id)} onMove={next=>moveJob(job,next)} onQuote={event=>submitQuote(event,job)} onMessage={event=>sendJobMessage(event,job)} onReview={event=>submitReview(event,job)}/>): <div className="qh-empty qh-empty-compact"><span><CalendarClock size={19}/></span><h3>No service requests yet</h3><p>Choose a Handi above to start a local service request.</p></div>}</div>
   <div className="qh-safety"><ShieldAlert size={16}/><span>Preview profiles and stats are examples, not verified people or live availability. Confirm details and price directly before arranging a real service.</span></div>
   </>:<JobsBoard mode="customer" currentEcoId="@philipk" currentName="Philip K." profile={store.ownProfile} jobs={store.customJobs} onCreate={createJob} onOffer={addJobOffer} onSelect={chooseJobOffer} onMove={moveCustomJob}/>}
  </>:<HandiMode profile={store.ownProfile} jobs={store.requests.filter(job=>store.ownProfile&&job.providerId===store.ownProfile.id)} onBecome={()=>setBecomeHandi(true)} onCustomer={()=>setMode('customer')} onExpand={id=>setActiveJob(activeJob===id?null:id)} activeJob={activeJob} quote={quote} setQuote={setQuote} quoteNote={quoteNote} setQuoteNote={setQuoteNote} chatText={chatText} setChatText={setChatText} onMove={moveJob} onQuote={submitQuote} onMessage={sendJobMessage} customJobs={store.customJobs} currentEcoId={store.ownProfile?.ecoId||'@philipk'} currentName={store.ownProfile?.businessName||store.ownProfile?.name||'Philip K.'} onCreate={createJob} onOffer={addJobOffer} onSelect={chooseJobOffer} onMoveCustom={moveCustomJob}/>}
  {requestFor&&<RequestModal profile={requestFor} onClose={()=>setRequestFor(null)} onSubmit={submitRequest}/>}
  {becomeHandi&&<HandiModal onClose={()=>setBecomeHandi(false)} onSubmit={submitProvider}/>}
  {toast&&<div className="qh-toast" role="status"><Check size={15}/>{toast}</div>}
 </div>;
}
function ProviderCard({profile,expanded,onExpand,onRequest}:{profile:HandiProfile;expanded:boolean;onExpand:()=>void;onRequest:()=>void}){
 return <article className="qh-provider-card"><div className="qh-provider-top"><div className="qh-provider-avatar">{profile.name.split(' ').map(part=>part[0]).join('').slice(0,2)}</div><div className="qh-provider-name"><span className="eyebrow">{profile.category.toUpperCase()} · {profile.area.toUpperCase()}</span><h3>{profile.businessName||profile.name}</h3><p>{profile.businessName?`${profile.name} · ${profile.ecoId}`:profile.ecoId} · {(profile.providerType||'individual').replace('-', ' ')}</p></div><button className="qh-more" onClick={onExpand} aria-expanded={expanded} aria-label="View service provider details">{expanded?<X size={17}/>:<ChevronDown size={17}/>}</button></div><p className="qh-provider-bio">{profile.bio}</p><div className="qh-service-tags">{profile.services.slice(0,3).map(service=><span key={service}>{service}</span>)}</div><div className="qh-facts"><span><Star size={14}/><b>{profile.rating?.toFixed(1)||'New'}</b><small>sample · {profile.reviewCount} reviews</small></span><span><Wrench size={14}/><b>{profile.completedJobs}</b><small>sample jobs</small></span><span><Clock3 size={14}/><b>{profile.responseTime.replace('Usually replies in ','')}</b><small>sample response</small></span></div>{expanded&&<div className="qh-provider-expanded"><span><MapPin size={14}/>Service area: {profile.area} · within {profile.serviceRadiusKm} km</span><span><BadgeCheck size={14}/>Verification: {profile.verification==='unverified'?'Not verified':profile.verification}</span><span><CalendarClock size={14}/>{profile.availability}</span><p>{profile.pricing==='quote'?'Quote-based service. Confirm a price before booking.':`${profile.pricing==='from'?'Indicative starting price':'Indicative sample price'}: ${formatGhs(profile.estimateMinor)} · not a binding quote.`}</p>{profile.sample&&<small>Example profile for design preview · rating and history are fictional.</small>}</div>}<div className="qh-provider-footer"><span><b>{formatGhs(profile.estimateMinor)}</b><small>{profile.pricing==='quote'?'Sample estimate · request a quote':profile.pricing==='from'?'Sample rate · from':'Sample fixed rate'}</small></span><button className="qh-outline-action" onClick={onExpand}>Compare details</button><button className="qh-primary-action" onClick={onRequest}>Request service <ArrowRight size={14}/></button></div></article>;
}
function RequestModal({profile,onClose,onSubmit}:{profile:HandiProfile;onClose:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){
 const [timing,setTiming]=useState<'asap'|'scheduled'>('asap');
 return <div className="qh-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><form className="qh-modal" onSubmit={onSubmit}><div className="qh-modal-head"><div><span className="eyebrow">NEW REQUEST · {profile.name}</span><h2>Tell them what you need</h2><p>{profile.category} · {profile.area}</p></div><button type="button" onClick={onClose} aria-label="Close request form"><X size={19}/></button></div><label>Short title<input name="title" maxLength={90} required placeholder="e.g. Fix a leaking kitchen pipe" defaultValue={profile.services[0]}/></label><label>Job details<textarea name="details" required maxLength={700} rows={3} placeholder="Share the useful details. Avoid adding sensitive payment information."/></label><div className="qh-form-row"><label>Service area<input name="area" required maxLength={100} defaultValue={profile.area} placeholder="Neighbourhood or town"/></label><label>Timing<select name="timing" value={timing} onChange={event=>setTiming(event.target.value as 'asap'|'scheduled')}><option value="asap">As soon as possible</option><option value="scheduled">Schedule for later</option></select></label></div>{timing==='scheduled'&&<label>Preferred date and time<input type="datetime-local" name="scheduledAt" required/></label>}<div className="qh-modal-price"><span>Sample estimate · confirm terms with the Handi</span><b>{formatGhs(profile.estimateMinor)}</b></div><div className="qh-modal-foot"><p><MapPin size={14}/>Only your service area is included in this local preview.</p><button type="submit" className="qh-primary-action">Send request <ArrowRight size={15}/></button></div></form></div>;
}
function HandiModal({onClose,onSubmit}:{onClose:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){
 return <div className="qh-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><form className="qh-modal" onSubmit={onSubmit}><div className="qh-modal-head"><div><span className="eyebrow">GROW WITH ECOVIBES</span><h2>Become a Handi</h2><p>Set up a local preview profile using your EcoVibes ID.</p></div><button type="button" onClick={onClose} aria-label="Close provider profile"><X size={19}/></button></div><label>Your name or business<input name="name" required maxLength={90} placeholder="Name shown to customers"/></label><div className="qh-form-row"><label>Provider type<select name="providerType" defaultValue="individual"><option value="individual">Individual Handi</option><option value="business">Small business</option><option value="company">Company</option><option value="team">Team</option></select></label><label>Team size, if relevant<input name="teamSize" type="number" min="1" max="500" placeholder="e.g. 5"/></label></div><label>Main service<input name="service" required maxLength={100} placeholder="e.g. Event photography"/></label><div className="qh-form-row"><label>Category<select name="category" defaultValue="Delivery & Errands">{serviceCategories.map(item=><option key={item}>{item}</option>)}</select></label><label>Service area<input name="area" required maxLength={100} placeholder="Town or neighbourhood"/></label></div><div className="qh-form-row"><label>Indicative price · GHS<input name="price" type="number" min="1" step="0.01" required placeholder="e.g. 120"/></label><label>Pricing approach<select name="pricing"><option value="quote">Quote after request</option><option value="from">Starting from</option><option value="fixed">Fixed sample price</option></select></label></div><p className="qh-form-disclaimer"><CircleHelp size={14}/>This saves a sample profile on this device. Verification, customer reach and payments are not active.</p><div className="qh-modal-foot"><button type="button" className="qh-text-action" onClick={onClose}>Cancel</button><button type="submit" className="qh-primary-action">Save profile <ArrowRight size={15}/></button></div></form></div>;
}
function JobCard({job,mode,expanded,quote,quoteNote,setQuote,setQuoteNote,chatText,setChatText,reviewText,setReviewText,rating,setRating,onToggle,onMove,onQuote,onMessage,onReview}:{job:ServiceRequest;mode:'customer'|'handi';expanded:boolean;quote:string;quoteNote:string;setQuote:(value:string)=>void;setQuoteNote:(value:string)=>void;chatText:string;setChatText:(value:string)=>void;reviewText:string;setReviewText:(value:string)=>void;rating:number;setRating:(value:number)=>void;onToggle:()=>void;onMove:(next:JobStatus)=>void;onQuote:(event:FormEvent<HTMLFormElement>)=>void;onMessage:(event:FormEvent<HTMLFormElement>)=>void;onReview:(event:FormEvent<HTMLFormElement>)=>void}){
 const canQuote=mode==='handi'&&job.status==='requested';
 return <article className="qh-job-card"><button className="qh-job-summary" onClick={onToggle} aria-expanded={expanded}><span className="qh-job-icon"><Wrench size={17}/></span><span className="qh-job-main"><small>{job.id} · {job.category}</small><b>{job.title}</b><i>{job.providerName} · {job.area} · {job.timing==='asap'?'ASAP':job.scheduledAt||'Scheduled'}</i></span><span className={`qh-job-status ${statusTone(job.status)}`}>{statusLabels[job.status]}</span><ChevronDown size={15}/></button>{expanded&&<div className="qh-job-detail"><div className="qh-job-facts"><span><b>Area</b>{job.area}</span><span><b>Price</b>{job.quoteMinor?formatGhs(job.quoteMinor):`${formatGhs(job.estimateMinor)} · sample estimate`}</span><span><b>Payment</b>Not connected</span></div><p className="qh-job-description">{job.details}</p>{job.quoteNote&&<div className="qh-quote-note"><b>Handi quote</b><span>{job.quoteNote} · {job.quoteMinor?formatGhs(job.quoteMinor):''}</span></div>}<div className="qh-timeline">{(['requested','accepted','confirmed','in_progress','awaiting_customer','completed'] as JobStatus[]).map((step,index)=><span key={step} className={['requested','accepted','confirmed','in_progress','awaiting_customer','completed'].indexOf(job.status)>=index?'past':''}><i>{index<5&&job.status==='completed'?<Check size={10}/>:index+1}</i><small>{['Requested','Accepted','Confirmed','In progress','Awaiting you','Complete'][index]}</small></span>)}</div>
 {canQuote&&<form className="qh-quote-form" onSubmit={onQuote}><b>Send a quote</b><div><span>GHS</span><input type="number" min="1" step="0.01" value={quote} onChange={event=>setQuote(event.target.value)} required placeholder="Amount"/><input value={quoteNote} onChange={event=>setQuoteNote(event.target.value)} maxLength={180} placeholder="Short note or what's included"/><button className="qh-primary-action">Send quote</button></div><small>Preview only · no payment or earnings are created.</small></form>}
 <div className="qh-job-actions">{mode==='handi'&&job.status==='requested'&&job.pricing!=='quote'&&<button className="qh-primary-action" onClick={()=>onMove('accepted')}>Accept request <Check size={14}/></button>}{mode==='customer'&&job.status==='quoted'&&<button className="qh-primary-action" onClick={()=>onMove('confirmed')}>Confirm quote <Check size={14}/></button>}{mode==='customer'&&job.status==='accepted'&&<button className="qh-primary-action" onClick={()=>onMove('confirmed')}>Confirm booking <Check size={14}/></button>}{mode==='handi'&&job.status==='quoted'&&<span className="qh-inline-hint">Waiting for customer response</span>}{mode==='handi'&&job.status==='confirmed'&&<button className="qh-primary-action" onClick={()=>onMove('in_progress')}>Start job <ArrowRight size={14}/></button>}{mode==='handi'&&job.status==='in_progress'&&<button className="qh-primary-action" onClick={()=>onMove('awaiting_customer')}>Mark as finished <Check size={14}/></button>}{mode==='customer'&&job.status==='awaiting_customer'&&<><button className="qh-primary-action" onClick={()=>onMove('completed')}>Confirm completion <Check size={14}/></button><button className="qh-outline-action" onClick={()=>onMove('disputed')}>Report an issue</button></>}{job.status==='requested'&&mode==='customer'&&<button className="qh-text-action" onClick={()=>onMove('cancelled')}>Cancel request</button>}{job.status==='completed'&&!job.review&&mode==='customer'&&<span className="qh-inline-hint">Leave a factual review below</span>}</div>
 {(job.status!=='cancelled')&&<div className="qh-chat"><div className="qh-chat-head"><MessageCircle size={14}/><b>Job messages</b><small>Keep payment details out of chat</small></div><div className="qh-messages">{job.messages.map(item=><p key={item.id} className={`qh-message ${item.sender}`}><span>{item.text}</span><small>{item.sender==='system'?'SYSTEM':item.sender==='handi'?'HANDI':'YOU'}</small></p>)}</div><form onSubmit={onMessage}><input value={chatText} onChange={event=>setChatText(event.target.value)} maxLength={500} aria-label="Write to the Handi" placeholder="Ask a question about this job…"/><button type="submit" disabled={!chatText.trim()}><ArrowRight size={15}/></button></form></div>}
 {job.status==='completed'&&job.review?<div className="qh-review-saved"><Star size={14}/> Your {job.rating}-star review is saved on this device: “{job.review}”</div>:job.status==='completed'&&mode==='customer'?<form className="qh-review-form" onSubmit={onReview}><label>Rate your experience <select value={rating} onChange={event=>setRating(Number(event.target.value))}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} stars</option>)}</select></label><input value={reviewText} onChange={event=>setReviewText(event.target.value)} maxLength={400} placeholder="Share a factual review"/><button className="qh-outline-action">Save review</button></form>:null}
 {['accepted','confirmed','in_progress','awaiting_customer','completed'].includes(job.status)&&<p className="qh-payment-note"><ShieldAlert size={14}/> Payments and escrow are not connected. Don’t send money through this preview.</p>}
 </div>}</article>;
}
function HandiMode({profile,jobs,onBecome,onCustomer,onExpand,activeJob,quote,setQuote,quoteNote,setQuoteNote,chatText,setChatText,onMove,onQuote,onMessage,customJobs,currentEcoId,currentName,onCreate,onOffer,onSelect,onMoveCustom}:{profile?:HandiProfile;jobs:ServiceRequest[];onBecome:()=>void;onCustomer:()=>void;onExpand:(id:string)=>void;activeJob:string|null;quote:string;setQuote:(value:string)=>void;quoteNote:string;setQuoteNote:(value:string)=>void;chatText:string;setChatText:(value:string)=>void;onMove:(job:ServiceRequest,next:JobStatus)=>void;onQuote:(event:FormEvent<HTMLFormElement>,job:ServiceRequest)=>void;onMessage:(event:FormEvent<HTMLFormElement>,job:ServiceRequest)=>void;customJobs:CustomJob[];currentEcoId:string;currentName:string;onCreate:(input:NewJobInput)=>void;onOffer:(job:CustomJob,input:NewOfferInput)=>void;onSelect:(job:CustomJob,offer:JobOffer)=>void;onMoveCustom:(job:CustomJob,next:CustomJobStatus)=>void}){
 return <><div className="qh-handi-hero"><div><span className="eyebrow">HANDI WORKSPACE · DEVICE PREVIEW</span><h2>Make good work<br/>easier to find.</h2><p>Manage local service enquiries from the EcoVibes identity you already use.</p>{profile?<button onClick={onCustomer}><ArrowLeft size={14}/> Back to customer mode</button>:<button onClick={onBecome}>Create your Handi profile <ArrowRight size={14}/></button>}</div><div className="qh-handi-orb" aria-hidden="true"><span/><i/><Wrench size={27}/></div></div>{profile?<><div className="qh-profile-summary"><span className="qh-provider-avatar">{profile.name.split(' ').map(part=>part[0]).join('').slice(0,2)}</span><div><span className="eyebrow">YOUR SERVICE PROFILE · {profile.ecoId}</span><h3>{profile.name}</h3><p>{profile.category} · {profile.area} · {formatGhs(profile.estimateMinor)} sample estimate</p></div><span className="qh-verify-none">Not verified</span></div><div className="qh-list-heading"><div><h2>Service requests</h2><p>Respond to local preview requests with a quote or acceptance.</p></div><span className="qh-result-count">{jobs.length} on this device</span></div>{jobs.length?jobs.slice().reverse().map(job=><JobCard key={job.id} job={job} mode="handi" expanded={activeJob===job.id} quote={quote} quoteNote={quoteNote} setQuote={setQuote} setQuoteNote={setQuoteNote} chatText={chatText} setChatText={setChatText} reviewText="" setReviewText={()=>undefined} rating={5} setRating={()=>undefined} onToggle={()=>onExpand(job.id)} onMove={next=>onMove(job,next)} onQuote={event=>onQuote(event,job)} onMessage={event=>onMessage(event,job)} onReview={()=>undefined}/>):<div className="qh-empty qh-empty-compact"><span><CalendarClock size={19}/></span><h3>No requests for this profile</h3><p>Switch to Customer mode and create a request for your Handi profile to try the local booking flow.</p><button onClick={onCustomer}>Switch to customer mode</button></div>}</>:<div className="qh-empty qh-handimode-empty"><span><Users size={20}/></span><h3>Start with a service profile</h3><p>Use one EcoVibes identity as a customer and a Handi. Your preview profile stays on this device.</p><button onClick={onBecome}>Become a Handi <Plus size={14}/></button></div>}{profile&&<JobsBoard mode="handi" currentEcoId={currentEcoId} currentName={currentName} profile={profile} jobs={customJobs} onCreate={onCreate} onOffer={onOffer} onSelect={onSelect} onMove={onMoveCustom}/>}<div className="qh-safety"><ShieldAlert size={16}/><span>Customer names, job history, verification and earnings are not real in this local preview. No payout or payment is available.</span></div></>;
}
